-- ШИНЭ: "Санал хvсэлт" хэсэг — хэрэглэгч 3 төрлийн (санал/асуудал-гомдол/
-- шинэ гаргалт хvсэх) мессеж бичиж admin-д илгээнэ.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  category text not null default 'suggestion', -- suggestion | complaint | request
  manga_title text,
  message text not null,
  -- ШИНЭ: "Манга санал болгох" (category='request') vед хэрэглэгч зураг (жишээ
  -- нь cover reference) хавсаргаж болно — R2-д (upload-to-r2 edge function-оор) хадгална.
  image_url text,
  status text not null default 'open', -- open | resolved
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.users(id) on delete set null
);
alter table public.feedback add column if not exists image_url text;

alter table public.feedback
  drop constraint if exists feedback_message_length;
alter table public.feedback
  add constraint feedback_message_length check (char_length(message) <= 2000 and char_length(message) > 0);

alter table public.feedback
  drop constraint if exists feedback_category_check;
alter table public.feedback
  add constraint feedback_category_check check (category in ('suggestion', 'complaint', 'request'));

alter table public.feedback enable row level security;

drop policy if exists "feedback_insert_own" on public.feedback;
create policy "feedback_insert_own" on public.feedback for insert
  with check (auth.uid() = user_id);

drop policy if exists "feedback_select_own_or_staff" on public.feedback;
create policy "feedback_select_own_or_staff" on public.feedback for select
  using (auth.uid() = user_id or public.has_any_role(auth.uid(), array['admin','moderator']));

drop policy if exists "feedback_update_staff" on public.feedback;
create policy "feedback_update_staff" on public.feedback for update
  using (public.has_any_role(auth.uid(), array['admin','moderator']));

-- Спам хамгаалалт: comments-тэй адил зарчмаар 10 секунд тутам 1 удаа л бичиж болно.
create or replace function public.enforce_feedback_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1 from public.feedback f
    where f.user_id = new.user_id
      and f.created_at > now() - interval '10 seconds'
  ) then
    raise exception 'rate_limited';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_feedback_rate_limit on public.feedback;
create trigger trg_enforce_feedback_rate_limit
  before insert on public.feedback
  for each row execute function public.enforce_feedback_rate_limit();

create index if not exists feedback_user_idx on public.feedback (user_id, created_at desc);
create index if not exists feedback_status_idx on public.feedback (status, created_at desc);
