-- ШИНЭ: "Даалгавар" — admin тодорхой шаардлага (X сэтгэгдэл бичих, Y бvлэг
-- унших) бvхий даалгавар vvсгэж, гvйцэтгэсэн хэрэглэгчид "цэцэг" (💐 flower)
-- шагнана. Цэцгийг дараа нь (migration_37) тодорхой НЭГ VIP бvлгийг 3
-- хоногийн турш түр нээхэд зарцуулна — шууд VIP хоног биш.

alter table public.users add column if not exists flower_balance integer not null default 0;
alter table public.users
  drop constraint if exists users_flower_balance_check;
alter table public.users
  add constraint users_flower_balance_check check (flower_balance >= 0);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  -- 'comments'      = нийт бичсэн сэтгэгдлийн тоо
  -- 'chapters_read' = нийт уншсан (тэмдэглэгдсэн) бvлгийн тоо
  requirement_type text not null,
  requirement_count int not null,
  reward_flowers int not null default 1,
  is_active boolean not null default true,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ЗАСВАР (алдаа): хуучин "reward_vip_days" баганыг "reward_flowers" болгож
-- нэрлэдэг байсан ч, дээрх CREATE TABLE аль хэдийн "reward_flowers" нэртэйгээр
-- шинээр vvсгэдэг тул шинэ (анх удаа ажиллуулж буй) төсөл дээр "reward_vip_days"
-- багана огт байхгvй — RENAME хийхэд алдаа гарч, БvХ migration_35 script
-- (tasks/task_claims хvснэгт хамт) rollback хийгддэг байв. Одоо зөвхөн тэр
-- хуучин багана бодитоор байгаа vед л (жишээ нь хуучин төсөл шинэчлэгдэх vед)
-- нэрийг нь сольдог болгов.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'reward_vip_days'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'reward_flowers'
  ) then
    alter table public.tasks rename column reward_vip_days to reward_flowers;
  end if;
end $$;

alter table public.tasks
  drop constraint if exists tasks_requirement_type_check;
alter table public.tasks
  add constraint tasks_requirement_type_check check (requirement_type in ('comments', 'chapters_read'));

alter table public.tasks
  drop constraint if exists tasks_requirement_count_check;
alter table public.tasks
  add constraint tasks_requirement_count_check check (requirement_count > 0);

alter table public.tasks
  drop constraint if exists tasks_reward_vip_days_check;
alter table public.tasks
  drop constraint if exists tasks_reward_flowers_check;
alter table public.tasks
  add constraint tasks_reward_flowers_check check (reward_flowers > 0);

alter table public.tasks enable row level security;

drop policy if exists "tasks_select_active_or_staff" on public.tasks;
create policy "tasks_select_active_or_staff" on public.tasks for select
  using (is_active or public.has_any_role(auth.uid(), array['admin']));

drop policy if exists "tasks_write_admin" on public.tasks;
create policy "tasks_write_admin" on public.tasks for all
  using (public.has_any_role(auth.uid(), array['admin']))
  with check (public.has_any_role(auth.uid(), array['admin']));

-- Хэрэглэгч тухайн даалгаврыг НЭГ л удаа шагналд авсан эсэхийг бvртгэнэ.
create table if not exists public.task_claims (
  user_id uuid not null references public.users(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  claimed_at timestamptz not null default now(),
  primary key (user_id, task_id)
);

alter table public.task_claims enable row level security;

drop policy if exists "task_claims_select_own" on public.task_claims;
create policy "task_claims_select_own" on public.task_claims for select
  using (auth.uid() = user_id);

-- ЗАСВАР: шагналыг клиент талд шууд users.flower_balance рvv бичих боломжгvй
-- (RLS-ээр хориглосон) тул шалгалт+шагнахыг НЭГ security definer RPC дотор
-- transaction-той хийнэ — approve_payment_request-тэй адил зарчим.
create or replace function public.claim_task(task_id_in bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  t record;
  progress_count int;
begin
  select * into t from public.tasks where id = task_id_in and is_active;
  if t is null then
    raise exception 'Даалгавар олдсонгvй';
  end if;

  if exists (select 1 from public.task_claims where user_id = auth.uid() and task_id = task_id_in) then
    raise exception 'already_claimed';
  end if;

  if t.requirement_type = 'comments' then
    select count(*) into progress_count from public.comments where user_id = auth.uid();
  elsif t.requirement_type = 'chapters_read' then
    select coalesce(sum(coalesce(array_length(read_chapters, 1), 0)), 0) into progress_count
      from public.reading_progress where user_id = auth.uid();
  else
    raise exception 'unknown_requirement_type';
  end if;

  if progress_count < t.requirement_count then
    raise exception 'not_enough_progress';
  end if;

  insert into public.task_claims (user_id, task_id) values (auth.uid(), task_id_in);

  update public.users
    set flower_balance = flower_balance + t.reward_flowers
    where id = auth.uid();
end;
$$;

grant execute on function public.claim_task(bigint) to authenticated;

create index if not exists tasks_active_idx on public.tasks (is_active);
