-- ЗАСВАР #16: ЭНЭ ФАЙЛ ТАНЫ SUPABASE ТӨСЛИЙГ App.jsx-ИЙН ХҮЛЭЭЖ БУЙ БҮТЭЦТЭЙ
-- ТОХИРУУЛЖ БҮРЭН ТОХИРГОО ХИЙНЭ.
--
-- Одоогийн байдлаар таны "public" schema-д ганцхан "rosellemanga" хүснэгт
-- байгаа бөгөөд түүнд НЭГ Ч БАГАНА байхгүй (яг л хоосон сав). chapters,
-- users, comments, comment_likes, reports хүснэгтүүд огт байхгүй.
--
-- Энэ script нь:
--   1) хоосон rosellemanga-г устгаад, mangas хүснэгтийг зөв баганатай нь үүсгэнэ
--   2) chapters, chapter_images, users, comments, comment_likes, reports хүснэгтүүдийг үүсгэнэ
--   3) шинээр бүртгүүлэх бүрт public.users мөр автоматаар үүсгэдэг trigger нэмнэ
--   4) role escalation-оос хамгаалах trigger нэмнэ (зөвхөн admin role өөрчилж чадна)
--   5) бүх хүснэгтэд RLS policy тохируулна
--   6) "manga-site" storage bucket болон upload/read эрхийг тохируулна
--
-- Ажиллуулахаас өмнө: rosellemanga хүснэгт хоосон (0 багана, өгөгдөлгүй)
-- гэдгийг би REST API-аар шалгаад баталгаажуулсан тул устгахад дата алдагдахгүй.
-- Supabase Dashboard → SQL Editor-т бүхлээр нь ГАРААР ажиллуулна уу.

-- ============================================================
-- 1) MANGAS
-- ============================================================
drop table if exists public.rosellemanga;

create table if not exists public.mangas (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  -- ЗАСВАР #56: 1-3 төрөл зэрэг байж болно (жишээ нь: Action + Historical)
  genres text[] not null default '{}',
  status text not null default 'Үргэлжилж байна',
  poster_url text,
  banner_url text,
  is_hidden boolean not null default false,
  schedule_day smallint,
  schedule_time text,
  views integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  -- ЗАСВАР #67: admin манга хуудсанд бичдэг тэмдэглэл (орчуулагчийн нэр гэх мэт)
  admin_note text,
  -- ЗАСВАР #71: нүүр хэсгийн "Санал болгох" hero-д admin гараар сонгосон эсэх
  is_recommended boolean not null default false,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 2) USERS (auth.users-той 1:1 профайл хүснэгт)
-- ============================================================
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  avatar_url text,
  -- ЗАСВАР #31: нэг утгатай role биш, олон эрхийг ЗЭРЭГ барих боломжтой массив
  -- (жишээ нь moderator+editor хамт байж болно)
  roles text[] not null default '{}',
  -- ЗАСВАР #20: VIP-г roles-оос тусад нь, дуусах хугацаатайгаар хадгална
  is_vip boolean not null default false,
  vip_expires_at timestamptz,
  -- ЗАСВАР #10 (migration_10): хэрэглэгчийн сэтгэгдэлд ашиглах 3 хvртэлх стикер
  sticker_1 text,
  sticker_2 text,
  sticker_3 text,
  created_at timestamptz not null default now()
);

-- Шинэ хэрэглэгч бүртгүүлэх бүрт public.users мөрийг автоматаар үүсгэнэ
-- (үгүй бол нэвтэрсний дараа role/name татах query үргэлж хоосон буцна).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- 3) CHAPTERS
-- ============================================================
create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  chapter_number numeric not null,
  title text,
  is_vip boolean not null default false,
  is_hidden boolean not null default false,
  status text not null default 'published', -- pending | published | rejected
  thumbnail_url text,
  -- ЗАСВАР #60: "ҮНЭГҮЙ"/"VIP" бэлгэдлийн оронд admin-ийн бичдэг дурын тэмдэглэгээ
  label text,
  publish_at timestamptz,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 4) CHAPTER_IMAGES
-- ============================================================
create table if not exists public.chapter_images (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  image_url text not null,
  page_number integer not null
);

-- ============================================================
-- 5) COMMENTS (parent_id — өөрөө рүүгээ холбогдож хариулт болно)
-- ============================================================
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  -- ЗАСВАР #11 (migration_11): манганы ерөнхий (chapter-гvй) сэтгэгдэлд зориулж nullable болгов
  chapter_id bigint references public.chapters(id) on delete cascade,
  manga_id bigint references public.mangas(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  content text not null,
  parent_id bigint references public.comments(id) on delete cascade,
  -- ЗАСВАР #10 (migration_10): хэрэглэгчийн профайл дахь стикерийг сэтгэгдэлд хавсаргах
  sticker_url text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 6) COMMENT_LIKES
-- ============================================================
create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

-- ЗАСВАР #11 (migration_11): манганд уншигчдын өгсөн 1-10 vнэлгээ
create table if not exists public.manga_ratings (
  user_id uuid not null references public.users(id) on delete cascade,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  score smallint not null check (score between 1 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, manga_id)
);

-- ============================================================
-- 7) REPORTS
-- ============================================================
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  comment_id bigint references public.comments(id) on delete set null,
  reporter_id uuid not null references public.users(id) on delete cascade,
  reason text,
  status text not null default 'open', -- open | resolved
  created_at timestamptz not null default now()
);

-- ЗАСВАР #8 (migration_8): "Төлбөр төлсөн" хүсэлт — admin шалгаад батлах/цуцлах
create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  plan_key text not null,
  status text not null default 'pending', -- pending | approved | rejected
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.users(id)
);

-- ЗАСВАР #9 (migration_9): "Хадгалсан манга"/"Түүх"/"Уншсан бүлэг" — localStorage-с шилжив
create table if not exists public.user_library (
  user_id uuid not null references public.users(id) on delete cascade,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, manga_id)
);

create table if not exists public.reading_progress (
  user_id uuid not null references public.users(id) on delete cascade,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  last_chapter numeric not null,
  read_chapters numeric[] not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (user_id, manga_id)
);

-- ============================================================
-- 8) Үзэлт (views) — атомаар нэмэгдүүлэх функц + сүүлийн 30 хоногийн
--    цаг тэмдэгтэй бүртгэл (нүүр хэсгийн "Санал болгох" мөрийг тооцоход)
-- ============================================================
create table if not exists public.manga_view_events (
  id bigint generated by default as identity primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  viewed_at timestamptz not null default now()
);
-- Энэ хүснэгтэд ЗӨВХӨН доорх security definer функцүүдээр л хандана (RLS-д
-- policy огт нэмээгүй тул шууд REST-ээр select/insert хийх боломжгүй).
alter table public.manga_view_events enable row level security;

-- ЗАСВАР: security definer болгосон — эс тэгвэл mangas_update_staff RLS
-- policy-нд хамаарч, staff биш энгийн уншигчийн үзэлт бодитоор нэмэгддэггүй байсан.
create or replace function public.increment_manga_views(input_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.mangas set views = views + 1 where id = input_id;
  insert into public.manga_view_events (manga_id) values (input_id);
end;
$$;

grant execute on function public.increment_manga_views(bigint) to anon, authenticated;

-- Сүүлийн N хоногт хамгийн их үзэгдсэн K мангаг буцаана
create or replace function public.top_manga_last_days(days_back int default 30, result_limit int default 10)
returns table(manga_id bigint, recent_views bigint)
language sql
stable
security definer
set search_path = public
as $$
  select manga_id, count(*) as recent_views
  from public.manga_view_events
  where viewed_at > now() - (days_back || ' days')::interval
  group by manga_id
  order by recent_views desc
  limit result_limit;
$$;

grant execute on function public.top_manga_last_days(int, int) to anon, authenticated;

-- ============================================================
-- 9) users.roles-ийг зөвхөн admin өөрчилж чадахаар хамгаална
-- ============================================================
create or replace function public.prevent_role_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- auth.uid() нь NULL байвал энэ бол SQL Editor эсвэл service_role-оор хийгдэж буй
  -- итгэмжлэгдсэн (trusted) өөрчлөлт гэсэн үг тул чөлөөтэй зөвшөөрнө. Харин browser-ээс
  -- нэвтэрсэн энгийн (admin биш) хэрэглэгч өөрийгөө/бусдыг admin болгохыг хориглоно.
  if new.roles is distinct from old.roles then
    if auth.uid() is not null and not exists (
      select 1 from public.users u where u.id = auth.uid() and 'admin' = any(u.roles)
    ) then
      new.roles := old.roles;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_role_escalation on public.users;
create trigger trg_prevent_role_escalation
  before update on public.users
  for each row execute function public.prevent_role_escalation();

-- ============================================================
-- 10) RLS идэвхжүүлэх + policy-үүд
-- ============================================================
alter table public.mangas enable row level security;
alter table public.users enable row level security;
alter table public.chapters enable row level security;
alter table public.chapter_images enable row level security;
alter table public.comments enable row level security;
alter table public.comment_likes enable row level security;
alter table public.reports enable row level security;
alter table public.manga_ratings enable row level security;
alter table public.payment_requests enable row level security;
alter table public.user_library enable row level security;
alter table public.reading_progress enable row level security;

-- users
drop policy if exists "users_select_all" on public.users;
create policy "users_select_all" on public.users for select using (true);

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own" on public.users for update
  using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "users_update_by_admin" on public.users;
create policy "users_update_by_admin" on public.users for update
  using (exists (select 1 from public.users u where u.id = auth.uid() and 'admin' = any(u.roles)))
  with check (true);

-- mangas
drop policy if exists "mangas_select" on public.mangas;
create policy "mangas_select" on public.mangas for select
  using (
    coalesce(is_hidden, false) = false
    or exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator','editor'])
  );

drop policy if exists "mangas_insert_staff" on public.mangas;
create policy "mangas_insert_staff" on public.mangas for insert
  with check (exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator','editor']));

drop policy if exists "mangas_update_staff" on public.mangas;
create policy "mangas_update_staff" on public.mangas for update
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator','editor']));

-- chapters
drop policy if exists "chapters_select" on public.chapters;
create policy "chapters_select" on public.chapters for select
  using (
    status = 'published'
    or exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator','editor'])
  );

drop policy if exists "chapters_insert_staff" on public.chapters;
create policy "chapters_insert_staff" on public.chapters for insert
  with check (exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator','editor']));

drop policy if exists "chapters_update_moderate" on public.chapters;
create policy "chapters_update_moderate" on public.chapters for update
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator']));

drop policy if exists "chapters_delete_moderate" on public.chapters;
create policy "chapters_delete_moderate" on public.chapters for delete
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator']));

-- chapter_images (published бүлгийн зургийг хэн ч харна; staff бүгдийг)
drop policy if exists "chapter_images_select" on public.chapter_images;
create policy "chapter_images_select" on public.chapter_images for select
  using (
    exists (
      select 1 from public.chapters c
      where c.id = chapter_id
        and (c.status = 'published' or exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator','editor']))
    )
  );

drop policy if exists "chapter_images_insert_staff" on public.chapter_images;
create policy "chapter_images_insert_staff" on public.chapter_images for insert
  with check (exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator','editor']));

-- comments
drop policy if exists "comments_select_all" on public.comments;
create policy "comments_select_all" on public.comments for select using (true);

drop policy if exists "comments_insert_own" on public.comments;
create policy "comments_insert_own" on public.comments for insert
  with check (auth.uid() = user_id);

drop policy if exists "comments_delete_own_or_mod" on public.comments;
create policy "comments_delete_own_or_mod" on public.comments for delete
  using (
    auth.uid() = user_id
    or exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator'])
  );

-- comment_likes
drop policy if exists "comment_likes_select_all" on public.comment_likes;
create policy "comment_likes_select_all" on public.comment_likes for select using (true);

drop policy if exists "comment_likes_insert_own" on public.comment_likes;
create policy "comment_likes_insert_own" on public.comment_likes for insert
  with check (auth.uid() = user_id);

drop policy if exists "comment_likes_delete_own" on public.comment_likes;
create policy "comment_likes_delete_own" on public.comment_likes for delete
  using (auth.uid() = user_id);

-- reports
drop policy if exists "reports_insert_own" on public.reports;
create policy "reports_insert_own" on public.reports for insert
  with check (auth.uid() = reporter_id);

drop policy if exists "reports_select_mod" on public.reports;
create policy "reports_select_mod" on public.reports for select
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator']));

drop policy if exists "reports_update_mod" on public.reports;
create policy "reports_update_mod" on public.reports for update
  using (exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator']));

-- payment_requests
drop policy if exists "payment_requests_insert_own" on public.payment_requests;
create policy "payment_requests_insert_own" on public.payment_requests for insert
  with check (auth.uid() = user_id);

drop policy if exists "payment_requests_select_own_or_admin" on public.payment_requests;
create policy "payment_requests_select_own_or_admin" on public.payment_requests for select
  using (
    auth.uid() = user_id
    or exists (select 1 from public.users u where u.id = auth.uid() and 'admin' = any(u.roles))
  );

drop policy if exists "payment_requests_update_admin" on public.payment_requests;
create policy "payment_requests_update_admin" on public.payment_requests for update
  using (exists (select 1 from public.users u where u.id = auth.uid() and 'admin' = any(u.roles)));

-- user_library / reading_progress
drop policy if exists "user_library_own" on public.user_library;
create policy "user_library_own" on public.user_library for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "reading_progress_own" on public.reading_progress;
create policy "reading_progress_own" on public.reading_progress for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- manga_ratings
drop policy if exists "manga_ratings_select_all" on public.manga_ratings;
create policy "manga_ratings_select_all" on public.manga_ratings for select using (true);

drop policy if exists "manga_ratings_own" on public.manga_ratings;
create policy "manga_ratings_own" on public.manga_ratings for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ============================================================
-- 11) STORAGE — "manga-site" bucket (avatar/poster/banner/chapter зургууд)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('manga-site', 'manga-site', true)
on conflict (id) do nothing;

drop policy if exists "manga_site_public_read" on storage.objects;
create policy "manga_site_public_read" on storage.objects for select
  using (bucket_id = 'manga-site');

-- avatars/ — нэвтэрсэн хэн ч өөрийн зургаа оруулж болно
drop policy if exists "manga_site_avatar_upload" on storage.objects;
create policy "manga_site_avatar_upload" on storage.objects for insert
  with check (
    bucket_id = 'manga-site'
    and (storage.foldername(name))[1] = 'avatars'
    and auth.role() = 'authenticated'
  );

-- posters/ banners/ chapters/ — зөвхөн staff
drop policy if exists "manga_site_staff_upload" on storage.objects;
create policy "manga_site_staff_upload" on storage.objects for insert
  with check (
    bucket_id = 'manga-site'
    and (storage.foldername(name))[1] in ('posters', 'banners', 'chapters')
    and exists (select 1 from public.users u where u.id = auth.uid() and u.roles && array['admin','moderator','editor'])
  );

-- Анхны admin-аа гараар тохируулна уу (доор жишээ — өөрийн имэйлээр солино):
-- update public.users set roles = array['admin'] where email = 'ТАНЫ_ИМЭЙЛ@жишээ.com';
