-- ШИНЭ: "Цэцэг" (💐) валютаар VIP бvлгийг ТvР (3 хоногийн турш) нээх систем.
-- migration_35-аар "Даалгавар" биелvvлэхэд хэрэглэгч цэцэг олдог болсон —
-- энд тэр цэцгийг зарцуулж, дурын НЭГ VIP бvлгийг 3 хоногийн турш VIP биш
-- атлаа уншиж чадахаар нээх RPC + холбогдох хvснэгт/policy-г нэмнэ.

create table if not exists public.chapter_unlocks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create unique index if not exists chapter_unlocks_user_chapter_idx on public.chapter_unlocks (user_id, chapter_id);
create index if not exists chapter_unlocks_expiry_idx on public.chapter_unlocks (chapter_id, expires_at);

alter table public.chapter_unlocks enable row level security;

drop policy if exists "chapter_unlocks_select_own" on public.chapter_unlocks;
create policy "chapter_unlocks_select_own" on public.chapter_unlocks for select
  using (auth.uid() = user_id);

-- ЗАСВАР: шалгалт (vлдэгдэл хvрэлцэх vv, аль хэдийн нээлттэй эсэх) + зарцуулах
-- (flower_balance хасах, chapter_unlocks мөр vvсгэх)-ийг НЭГ transaction-той
-- security definer RPC дотор хийнэ — claim_task/approve_payment_request-тэй адил зарчим.
create or replace function public.unlock_chapter_with_flower(chapter_id_in bigint)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  ch record;
  existing record;
  new_expires timestamptz;
begin
  select * into ch from public.chapters where id = chapter_id_in;
  if ch is null then
    raise exception 'Бvлэг олдсонгvй';
  end if;
  if not ch.is_vip then
    raise exception 'Энэ бvлэг VIP бvлэг биш тул цэцгээр нээх шаардлагагvй';
  end if;

  select * into existing from public.chapter_unlocks where user_id = auth.uid() and chapter_id = chapter_id_in;
  if existing is not null and existing.expires_at > now() then
    raise exception 'already_unlocked';
  end if;

  if not exists (select 1 from public.users u where u.id = auth.uid() and u.flower_balance > 0) then
    raise exception 'not_enough_flowers';
  end if;

  update public.users set flower_balance = flower_balance - 1 where id = auth.uid();

  new_expires := now() + interval '3 days';
  insert into public.chapter_unlocks (user_id, chapter_id, unlocked_at, expires_at)
    values (auth.uid(), chapter_id_in, now(), new_expires)
    on conflict (user_id, chapter_id) do update set unlocked_at = now(), expires_at = new_expires;

  return new_expires;
end;
$$;

grant execute on function public.unlock_chapter_with_flower(bigint) to authenticated;

-- ЗАСВАР: chapter_images-ийн унших эрхийг (VIP шалгалт) идэвхтэй
-- chapter_unlocks мөртэй хэрэглэгчид ч нээж өгнө — VIP биш атлаа цэцгээр
-- тухайн НЭГ бvлгийг л 3 хоногийн турш уншиж болно.
drop policy if exists "chapter_images_select" on public.chapter_images;
create policy "chapter_images_select" on public.chapter_images for select
  using (
    exists (
      select 1 from public.chapters c
      where c.id = chapter_id
        and (
          public.has_any_role(auth.uid(), array['admin','moderator','editor'])
          or (
            c.status = 'published'
            and (c.publish_at is null or c.publish_at <= now())
            and (
              not c.is_vip
              or exists (
                select 1 from public.users u where u.id = auth.uid()
                  and u.is_vip and (u.vip_expires_at is null or u.vip_expires_at > now())
              )
              or exists (
                select 1 from public.chapter_unlocks cu
                where cu.user_id = auth.uid() and cu.chapter_id = c.id and cu.expires_at > now()
              )
            )
          )
        )
    )
  );
