-- ШИНЭ (хэрэглэгчийн хvсэлт): сар бvр шинэчлэгддэг "ЭРЭМБЭ" (уншсан бvлгээр
-- жагсаасан leaderboard) хуудас. reading_progress нь зөвхөн НИЙТ уншсан
-- бvлгийн жагсаалт хадгалдаг (огноогvй) тул сар бvрийн идэвхийг тооцох
-- боломжгvй байсан — иймд бvлэг уншсан vед бvр (шинээр уншсан vед л)
-- цаг timestamp-тай тэмдэглэдэг тусдаа vйл явдлын хvснэгт нэмнэ.

create table if not exists public.chapter_read_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  chapter_number numeric not null,
  read_at timestamptz not null default now()
);

-- Энэ хvснэгтэд ЗӨВХӨН доорх security definer функцvvдээр л хандана
-- (manga_view_events-тэй адил загвар — RLS-д select/insert policy
-- нэмээгvй тул шууд REST-ээр хандах боломжгvй, зөвхөн insert-ийг доор
-- тусад нь заавал зөвшөөрнө).
alter table public.chapter_read_events enable row level security;

drop policy if exists "chapter_read_events_insert_own" on public.chapter_read_events;
create policy "chapter_read_events_insert_own" on public.chapter_read_events for insert
  with check (auth.uid() = user_id);

create index if not exists chapter_read_events_month_idx on public.chapter_read_events (read_at, user_id);

-- ЗАСВАР (хэрэглэгчийн хvсэлт): бvлгийн ТООГООР биш, ОНООГООР эрэмбэлнэ —
-- 1 уншсан бvлэг = 3 оноо. Буцаах баганын нэрийг өөрчилсөн (chapters_count →
-- score) тул эхлээд хуучин функцийг drop хийнэ (RETURN TYPE өөрчлөгдсөн vед
-- бэлэн create or replace ажилладаггvй).
drop function if exists public.get_chapter_rank_leaderboard(int);
drop function if exists public.get_my_chapter_rank();

-- Энэ сарын (calendar month) хамгийн олон оноо цуглуулсан ТОП N хэрэглэгч.
create or replace function public.get_chapter_rank_leaderboard(limit_in int default 20)
returns table(user_id uuid, name text, avatar_url text, score bigint, rnk bigint)
language sql
stable
security definer
set search_path = public
as $$
  select u.id, u.name, u.avatar_url, t.score, t.rnk
  from (
    select e.user_id, count(*) * 3 as score,
           rank() over (order by count(*) desc) as rnk
    from public.chapter_read_events e
    where e.read_at >= date_trunc('month', now())
    group by e.user_id
  ) t
  join public.users u on u.id = t.user_id
  order by t.rnk
  limit limit_in;
$$;

grant execute on function public.get_chapter_rank_leaderboard(int) to authenticated;

-- Одоогийн хэрэглэгчийн энэ сарын эрэмбэ + оноо (ТОП 20-д ороогvй ч харагдана).
create or replace function public.get_my_chapter_rank()
returns table(score bigint, rnk bigint)
language sql
stable
security definer
set search_path = public
as $$
  select t.score, t.rnk
  from (
    select e.user_id, count(*) * 3 as score,
           rank() over (order by count(*) desc) as rnk
    from public.chapter_read_events e
    where e.read_at >= date_trunc('month', now())
    group by e.user_id
  ) t
  where t.user_id = auth.uid();
$$;

grant execute on function public.get_my_chapter_rank() to authenticated;
