-- ЗАСВАР #2: supabase_setup.sql-г НЭГ удаа ажиллуулсны дараа гарсан шинэ
-- шаардлагуудыг нэмж байгаа өсөлт (migration). Зөвхөн үүнийг ажиллуулахад
-- хангалттай — өмнөх бүтэн script-ийг дахин ажиллуулах шаардлагагүй
-- (учир нь users/mangas/chapters гэх мэт хүснэгтүүд аль хэдийн үүссэн тул
-- "create table if not exists" дахин ажиллуулахад шинэ баганыг нэмэхгүй).

-- ============================================================
-- 1) VIP-г role-оос тусад нь, дуусах хугацаатайгаар хадгалах
-- ============================================================
alter table public.users add column if not exists is_vip boolean not null default false;
alter table public.users add column if not exists vip_expires_at timestamptz;

-- ============================================================
-- 2) Сүүлийн 30 хоногийн үзэлтийн бүртгэл ("Санал болгох" мөрд ашиглана)
-- ============================================================
create table if not exists public.manga_view_events (
  id bigint generated by default as identity primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  viewed_at timestamptz not null default now()
);
alter table public.manga_view_events enable row level security;
-- Энд ЗОРИУДААР ямар ч policy нэмээгүй — зөвхөн доорх security definer
-- функцүүдээр л (increment_manga_views, top_manga_last_days) хандана.

-- ЗАСВАР: increment_manga_views-г security definer болгож, event бүртгэдэг
-- болгосон. Өмнөх хувилбар нь "language sql" (invoker rights) байсан тул
-- mangas_update_staff RLS policy-нд хамаарч, staff БИШ энгийн уншигчийн
-- үзэлтийг бодитоор нэмэгдүүлдэггүй нуугдмал алдаатай байсан.
create or replace function public.increment_manga_views(input_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.mangas set views = views + 1 where id = input_id;
  insert into public.manga_view_events (manga_id) values (input_id);
end;
$$;

grant execute on function public.increment_manga_views(bigint) to anon, authenticated;

create or replace function public.top_manga_last_days(days_back int default 30, result_limit int default 10)
returns table(manga_id bigint, recent_views bigint)
language sql
stable
security definer
set search_path = public
as $$
  select manga_id, count(*) as recent_views
  from public.manga_view_events
  where viewed_at > now() - (days_back || ' days')::interval
  group by manga_id
  order by recent_views desc
  limit result_limit;
$$;

grant execute on function public.top_manga_last_days(int, int) to anon, authenticated;
