-- ШИНЭ (хэрэглэгчийн хvсэлт): admin/moderator/editor хэрэглэгчид хvссэн
-- унших уншигчиддаа vнэгvй (өөрийн цэцгээс биш) цэцэг бэлэглэж болно —
-- сард нийт 30 цэцэгийн хязгаартайгаар (буруугаар ашиглахаас сэргийлнэ).

create table if not exists public.staff_flower_gifts (
  id bigint generated by default as identity primary key,
  staff_id uuid not null references public.users(id) on delete cascade,
  recipient_id uuid not null references public.users(id) on delete cascade,
  amount int not null,
  created_at timestamptz not null default now()
);

alter table public.staff_flower_gifts
  drop constraint if exists staff_flower_gifts_amount_check;
alter table public.staff_flower_gifts
  add constraint staff_flower_gifts_amount_check check (amount > 0);

alter table public.staff_flower_gifts enable row level security;

drop policy if exists "staff_flower_gifts_select_own" on public.staff_flower_gifts;
create policy "staff_flower_gifts_select_own" on public.staff_flower_gifts for select
  using (auth.uid() = staff_id or public.has_any_role(auth.uid(), array['admin']));

create index if not exists staff_flower_gifts_staff_created_idx on public.staff_flower_gifts (staff_id, created_at);

-- ЗАСВАР: шалгалт (эрх, хязгаар, блоклолт) + шилжvvлэлт нэг transaction-той RPC дотор.
create or replace function public.gift_flowers_as_staff(recipient_id_in uuid, amount_in int)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  used int;
begin
  if not public.has_any_role(auth.uid(), array['admin', 'moderator', 'editor']) then
    raise exception 'not_staff';
  end if;
  if amount_in is null or amount_in <= 0 then
    raise exception 'invalid_amount';
  end if;
  if recipient_id_in = auth.uid() then
    raise exception 'cannot_gift_self';
  end if;
  if exists (
    select 1 from public.blocked_users
    where (blocker_id = recipient_id_in and blocked_id = auth.uid())
       or (blocker_id = auth.uid() and blocked_id = recipient_id_in)
  ) then
    raise exception 'blocked';
  end if;

  select coalesce(sum(amount), 0) into used from public.staff_flower_gifts
    where staff_id = auth.uid() and created_at >= date_trunc('month', now());
  if used + amount_in > 30 then
    raise exception 'quota_exceeded';
  end if;

  update public.users set flower_balance = flower_balance + amount_in where id = recipient_id_in;
  insert into public.staff_flower_gifts (staff_id, recipient_id, amount) values (auth.uid(), recipient_id_in, amount_in);
end;
$$;

grant execute on function public.gift_flowers_as_staff(uuid, int) to authenticated;

create or replace function public.get_staff_gift_quota_remaining()
returns int
language sql
security definer
set search_path = public
stable
as $$
  select greatest(0, 30 - coalesce((
    select sum(amount) from public.staff_flower_gifts
    where staff_id = auth.uid() and created_at >= date_trunc('month', now())
  ), 0));
$$;

grant execute on function public.get_staff_gift_quota_remaining() to authenticated;
