-- ЗАСВАР #8: "ТӨЛБӨР ТӨЛСӨН" хүсэлтийн хүснэгт — хэрэглэгч VIP багц сонгоод
-- гүйлгээ хийсний дараа "Төлбөр төлсөн" дарахад admin-д хүсэлт очиж,
-- admin шалгаад батлах (VIP олгох) эсвэл цуцлах боломжтой болно.
-- Supabase Dashboard → SQL Editor-т ГАРААР ажиллуулна уу.

create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  plan_key text not null,
  status text not null default 'pending', -- pending | approved | rejected
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.users(id)
);

alter table public.payment_requests enable row level security;

drop policy if exists "payment_requests_insert_own" on public.payment_requests;
create policy "payment_requests_insert_own" on public.payment_requests for insert
  with check (auth.uid() = user_id);

drop policy if exists "payment_requests_select_own_or_admin" on public.payment_requests;
create policy "payment_requests_select_own_or_admin" on public.payment_requests for select
  using (
    auth.uid() = user_id
    or exists (select 1 from public.users u where u.id = auth.uid() and 'admin' = any(u.roles))
  );

drop policy if exists "payment_requests_update_admin" on public.payment_requests;
create policy "payment_requests_update_admin" on public.payment_requests for update
  using (exists (select 1 from public.users u where u.id = auth.uid() and 'admin' = any(u.roles)));
