-- ШИНЭ (хэрэглэгчийн хvсэлт):
--   1) "Roselle уншигчид" (нийтийн чат) -г зөвхөн VIP (эсвэл staff) хэрэглэгчид
--      харах/бичих боломжтой болгоно.
--   2) chat_messages-д стикер илгээх дэмжлэг нэмнэ (одоог хvртэл текст ганцхан байсан).
--   3) gift_stickers — admin/moderator "тусгай хэсгээс" нэмдэг, БvХ хэрэглэгч
--      чатанд ашиглаж болох нийтийн стикерийн сан.

-- 1) gift_stickers -------------------------------------------------------
create table if not exists public.gift_stickers (
  id bigint generated by default as identity primary key,
  url text not null,
  created_by uuid references public.users(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.gift_stickers enable row level security;

drop policy if exists "gift_stickers_select_active" on public.gift_stickers;
create policy "gift_stickers_select_active" on public.gift_stickers for select
  using (is_active or public.has_any_role(auth.uid(), array['admin','moderator']));

drop policy if exists "gift_stickers_write_staff" on public.gift_stickers;
create policy "gift_stickers_write_staff" on public.gift_stickers for all
  using (public.has_any_role(auth.uid(), array['admin','moderator']))
  with check (public.has_any_role(auth.uid(), array['admin','moderator']));

-- 2) chat_messages-д стикер дэмжлэг ---------------------------------------
alter table public.chat_messages add column if not exists message_type text not null default 'text';
alter table public.chat_messages
  drop constraint if exists chat_messages_type_check;
alter table public.chat_messages
  add constraint chat_messages_type_check check (message_type in ('text', 'sticker'));

alter table public.chat_messages add column if not exists sticker_url text;

-- ЗАСВАР: message text (текст vед) заавал, sticker_url (стикер vед) заавал байхыг шалгана.
alter table public.chat_messages alter column message drop not null;

create or replace function public.validate_chat_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.message_type = 'text' and (new.message is null or length(trim(new.message)) = 0) then
    raise exception 'empty_message';
  end if;
  if new.message_type = 'sticker' and new.sticker_url is null then
    raise exception 'missing_sticker';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_validate_chat_message on public.chat_messages;
create trigger trg_validate_chat_message
  before insert on public.chat_messages
  for each row execute function public.validate_chat_message();

-- 3) "Roselle уншигчид" (public өрөө)-г зөвхөн VIP/staff-д нээлттэй болгоно --
drop policy if exists "chat_messages_select_public_or_staff" on public.chat_messages;
create policy "chat_messages_select_vip_public_or_staff" on public.chat_messages for select
  using (
    (
      room = 'public'
      and (
        public.has_any_role(auth.uid(), array['admin','moderator','editor'])
        or exists (
          select 1 from public.users u where u.id = auth.uid()
            and u.is_vip and (u.vip_expires_at is null or u.vip_expires_at > now())
        )
      )
    )
    or (room = 'staff' and public.has_any_role(auth.uid(), array['admin','moderator','editor']))
  );

drop policy if exists "chat_messages_insert_own_room_checked" on public.chat_messages;
create policy "chat_messages_insert_own_room_vip_checked" on public.chat_messages for insert
  with check (
    auth.uid() = user_id
    and (
      (
        room = 'public'
        and (
          public.has_any_role(auth.uid(), array['admin','moderator','editor'])
          or exists (
            select 1 from public.users u where u.id = auth.uid()
              and u.is_vip and (u.vip_expires_at is null or u.vip_expires_at > now())
          )
        )
      )
      or (room = 'staff' and public.has_any_role(auth.uid(), array['admin','moderator','editor']))
    )
  );
