-- ШИНЭ (хэрэглэгчийн хvсэлт): "Санал хvсэлт" хуудсанд 2 шинэ хэсэг:
--   1) Ажилтныг (editor/moderator/admin) урамшуулах — өөрийн "од"-оос
--      хvссэн тоогоороо бэлэглэж, урамшуулах vг бичих.
--   2) "Баг нэгдэх хvсэлт" — feedback хvснэгтийг vргэлжлvvлэн ашиглаж,
--      шинэ ангилал (category='team') + баг/танилцуулгын холбоос (link_url) нэмнэ.

-- 1) feedback: "team" ангилал + link_url --------------------------------
alter table public.feedback add column if not exists link_url text;

alter table public.feedback
  drop constraint if exists feedback_category_check;
alter table public.feedback
  add constraint feedback_category_check check (category in ('suggestion', 'complaint', 'request', 'team'));

-- 2) ажилтныг урамшуулах (staff_appreciations) --------------------------
create table if not exists public.staff_appreciations (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.users(id) on delete cascade,
  staff_id uuid not null references public.users(id) on delete cascade,
  amount int not null,
  message text,
  created_at timestamptz not null default now()
);

alter table public.staff_appreciations
  drop constraint if exists staff_appreciations_amount_check;
alter table public.staff_appreciations
  add constraint staff_appreciations_amount_check check (amount > 0);

alter table public.staff_appreciations
  drop constraint if exists staff_appreciations_message_length;
alter table public.staff_appreciations
  add constraint staff_appreciations_message_length check (message is null or char_length(message) <= 500);

alter table public.staff_appreciations enable row level security;

drop policy if exists "staff_appreciations_select_participant" on public.staff_appreciations;
create policy "staff_appreciations_select_participant" on public.staff_appreciations for select
  using (auth.uid() = sender_id or auth.uid() = staff_id or public.has_any_role(auth.uid(), array['admin']));

-- ЗАСВАР: хvн бvр админ/модератор/эдиторын жагсаалтыг (нэр/avatar/эрх) харах
-- шаардлагатай тул нээлттэй RPC-ээр өгнө (email мэт хувийн мэдээлэлгvй).
create or replace function public.get_staff_list()
returns table(id uuid, name text, avatar_url text, roles text[])
language sql
security definer
set search_path = public
stable
as $$
  select u.id, u.name, u.avatar_url, u.roles
  from public.users u
  where u.roles && array['admin','moderator','editor']
  order by (case when 'admin' = any(u.roles) then 0 when 'moderator' = any(u.roles) then 1 else 2 end), u.name;
$$;

grant execute on function public.get_staff_list() to authenticated;

-- ЗАСВАР: шалгалт (vлдэгдэл хvрэлцэх vv, тухайн хvн staff мөн эсэх) + шилжvvлэх
-- (өгөгчөөс хасах, staff-д нэмэх) + мессежийг НЭГ transaction-той RPC дотор хийнэ.
create or replace function public.gift_points_to_staff(staff_id_in uuid, amount_in int, message_in text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if amount_in is null or amount_in <= 0 then
    raise exception 'invalid_amount';
  end if;
  if staff_id_in = auth.uid() then
    raise exception 'cannot_gift_self';
  end if;
  if not public.has_any_role(staff_id_in, array['admin','moderator','editor']) then
    raise exception 'not_staff';
  end if;
  if not exists (select 1 from public.users u where u.id = auth.uid() and u.loyalty_points >= amount_in) then
    raise exception 'not_enough_points';
  end if;

  update public.users set loyalty_points = loyalty_points - amount_in where id = auth.uid();
  update public.users set loyalty_points = loyalty_points + amount_in where id = staff_id_in;

  insert into public.staff_appreciations (sender_id, staff_id, amount, message)
    values (auth.uid(), staff_id_in, amount_in, nullif(trim(message_in), ''));
end;
$$;

grant execute on function public.gift_points_to_staff(uuid, int, text) to authenticated;
