-- ЗАСВАР #16: ЭНЭ ФАЙЛ ТАНЫ SUPABASE ТӨСЛИЙГ App.jsx-ИЙН ХҮЛЭЭЖ БУЙ БҮТЭЦТЭЙ
-- ТОХИРУУЛЖ БҮРЭН ТОХИРГОО ХИЙНЭ.
--
-- Одоогийн байдлаар таны "public" schema-д ганцхан "rosellemanga" хүснэгт
-- байгаа бөгөөд түүнд НЭГ Ч БАГАНА байхгүй (яг л хоосон сав). chapters,
-- users, comments, comment_likes, reports хүснэгтүүд огт байхгүй.
--
-- Энэ script нь:
--   1) хоосон rosellemanga-г устгаад, mangas хүснэгтийг зөв баганатай нь үүсгэнэ
--   2) chapters, chapter_images, users, comments, comment_likes, reports хүснэгтүүдийг үүсгэнэ
--   3) шинээр бүртгүүлэх бүрт public.users мөр автоматаар үүсгэдэг trigger нэмнэ
--   4) role escalation-оос хамгаалах trigger нэмнэ (зөвхөн admin role өөрчилж чадна)
--   5) бүх хүснэгтэд RLS policy тохируулна
--   6) "manga-site" storage bucket болон upload/read эрхийг тохируулна
--
-- Ажиллуулахаас өмнө: rosellemanga хүснэгт хоосон (0 багана, өгөгдөлгүй)
-- гэдгийг би REST API-аар шалгаад баталгаажуулсан тул устгахад дата алдагдахгүй.
-- Supabase Dashboard → SQL Editor-т бүхлээр нь ГАРААР ажиллуулна уу.
--
-- ЗАСВАР #163 (код шинжилгээ): ЭНЭ ФАЙЛЫГ БvРЭН ШИНЭЧИЛЖ, migration_2-ээс
-- migration_26 хvртэлх (has_any_role, sticker_4-6, VIP-хамгаалалт, purge, FK
-- индекс гэх мэт) бvх зассан эцсийн байдлыг нэг дороос тусгасан "consolidated"
-- файл болгов. Тиймээс ШИНЭ (хоосон) Supabase төсөл дээр ЗӨВХӨН ЭНЭ файлыг
-- ажиллуулахад л хангалттай — migration_2..26-г дахин ажиллуулах шаардлагагvй
-- (тэдгээр нь зөвхөн ХУУЧИН (аль хэдийн ажиллаж байгаа) төслvvдэд дараалан
-- нэмэлт засвар оруулах зориулалттай, түvхэн бvртгэл болгож vлдээв).

-- ============================================================
-- 1) MANGAS
-- ============================================================
drop table if exists public.rosellemanga;

create table if not exists public.mangas (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  -- ЗАСВАР #56: 1-3 төрөл зэрэг байж болно (жишээ нь: Action + Historical)
  genres text[] not null default '{}',
  status text not null default 'Үргэлжилж байна',
  poster_url text,
  banner_url text,
  is_hidden boolean not null default false,
  schedule_day smallint,
  schedule_time text,
  views integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  -- ЗАСВАР #67: admin манга хуудсанд бичдэг тэмдэглэл (орчуулагчийн нэр гэх мэт)
  admin_note text,
  -- ЗАСВАР #71: нүүр хэсгийн "Санал болгох" hero-д admin гараар сонгосон эсэх
  is_recommended boolean not null default false,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 2) USERS (auth.users-той 1:1 профайл хүснэгт)
-- ============================================================
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  avatar_url text,
  -- ЗАСВАР #31: нэг утгатай role биш, олон эрхийг ЗЭРЭГ барих боломжтой массив
  -- (жишээ нь moderator+editor хамт байж болно)
  roles text[] not null default '{}',
  -- ЗАСВАР #20: VIP-г roles-оос тусад нь, дуусах хугацаатайгаар хадгална
  is_vip boolean not null default false,
  vip_expires_at timestamptz,
  -- ЗАСВАР #10 (migration_10) + #15 (migration_15): хэрэглэгчийн сэтгэгдэлд
  -- ашиглах 6 хvртэлх стикер (App.jsx-ийн stickerSlots үvнтэй тааруулсан байх ёстой)
  sticker_1 text,
  sticker_2 text,
  sticker_3 text,
  sticker_4 text,
  sticker_5 text,
  sticker_6 text,
  created_at timestamptz not null default now()
);

-- Шинэ хэрэглэгч бүртгүүлэх бүрт public.users мөрийг автоматаар үүсгэнэ
-- (үгүй бол нэвтэрсний дараа role/name татах query үргэлж хоосон буцна).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- 3) CHAPTERS
-- ============================================================
create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  chapter_number numeric not null,
  title text,
  is_vip boolean not null default false,
  is_hidden boolean not null default false,
  status text not null default 'published', -- pending | published | rejected
  thumbnail_url text,
  -- ЗАСВАР #60: "ҮНЭГҮЙ"/"VIP" бэлгэдлийн оронд admin-ийн бичдэг дурын тэмдэглэгээ
  label text,
  publish_at timestamptz,
  -- ЗАСВАР #125 (migration_13): moderator/editor "УСТГАХ ХvСЭЛТ" vvсгэдэг,
  -- admin л эцсийн баталгаажуулалт хийж бодитоор устгадаг 2 шатлалт хамгаалалт.
  pending_delete boolean not null default false,
  delete_requested_by uuid references public.users(id) on delete set null,
  delete_requested_at timestamptz,
  created_at timestamptz not null default now()
);
-- Хуучин (энэ баганагvйгээр аль хэдийн vvссэн) хvснэгт дээр ч найдвартай
-- ажиллахын тулд ("create table if not exists" шинэ багана нэмдэггvй тул):
alter table public.chapters add column if not exists pending_delete boolean not null default false;
alter table public.chapters add column if not exists delete_requested_by uuid references public.users(id) on delete set null;
alter table public.chapters add column if not exists delete_requested_at timestamptz;

-- ============================================================
-- 4) CHAPTER_IMAGES
-- ============================================================
create table if not exists public.chapter_images (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  image_url text not null,
  page_number integer not null
);

-- ============================================================
-- 5) COMMENTS (parent_id — өөрөө рүүгээ холбогдож хариулт болно)
-- ============================================================
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  -- ЗАСВАР #11 (migration_11): манганы ерөнхий (chapter-гvй) сэтгэгдэлд зориулж nullable болгов
  chapter_id bigint references public.chapters(id) on delete cascade,
  manga_id bigint references public.mangas(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  content text not null,
  parent_id bigint references public.comments(id) on delete cascade,
  -- ЗАСВАР #10 (migration_10): хэрэглэгчийн профайл дахь стикерийг сэтгэгдэлд хавсаргах
  sticker_url text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 6) COMMENT_LIKES
-- ============================================================
create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

-- ЗАСВАР #11 (migration_11): манганд уншигчдын өгсөн 1-10 vнэлгээ
create table if not exists public.manga_ratings (
  user_id uuid not null references public.users(id) on delete cascade,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  score smallint not null check (score between 1 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, manga_id)
);

-- ============================================================
-- 7) REPORTS
-- ============================================================
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  comment_id bigint references public.comments(id) on delete set null,
  reporter_id uuid not null references public.users(id) on delete cascade,
  reason text,
  status text not null default 'open', -- open | resolved
  created_at timestamptz not null default now()
);

-- ЗАСВАР #8 (migration_8): "Төлбөр төлсөн" хүсэлт — admin шалгаад батлах/цуцлах
create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  plan_key text not null,
  status text not null default 'pending', -- pending | approved | rejected
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.users(id),
  -- ЗАСВАР #163 (код шинжилгээ): хvсэлт илгээх vеийн (хямдралтай бол хямдарсан)
  -- vнийг тvvхэнд хадгална — хямдрал дуусаад ч ямар vнээр батлагдсаныг мэдэхээр.
  paid_price text
);

-- ЗАСВАР #9 (migration_9): "Хадгалсан манга"/"Түүх"/"Уншсан бүлэг" — localStorage-с шилжив
create table if not exists public.user_library (
  user_id uuid not null references public.users(id) on delete cascade,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, manga_id)
);

create table if not exists public.reading_progress (
  user_id uuid not null references public.users(id) on delete cascade,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  last_chapter numeric not null,
  read_chapters numeric[] not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (user_id, manga_id)
);

-- ============================================================
-- 8) Үзэлт (views) — атомаар нэмэгдүүлэх функц + сүүлийн 30 хоногийн
--    цаг тэмдэгтэй бүртгэл (нүүр хэсгийн "Санал болгох" мөрийг тооцоход)
-- ============================================================
create table if not exists public.manga_view_events (
  id bigint generated by default as identity primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  -- ЗАСВАР #139 (migration_22): тухайн (манга, vзэгч) хослол сvvлийн 30 минутад
  -- аль хэдийн бvртгэгдсэн эсэхийг шалгаж, script-ээр давтан дуудаж vзэлт хиймлээр
  -- өсгөхөөс сэргийлнэ. Нэвтэрсэн бол auth.uid(), зочинд browser-ийн санамсаргvй key.
  viewer_key text check (char_length(viewer_key) <= 64)
);
-- Энэ хүснэгтэд ЗӨВХӨН доорх security definer функцүүдээр л хандана (RLS-д
-- policy огт нэмээгүй тул шууд REST-ээр select/insert хийх боломжгүй).
alter table public.manga_view_events enable row level security;

create index if not exists manga_view_events_dedup_idx
  on public.manga_view_events (manga_id, viewer_key, viewed_at);
-- ЗАСВАР #163 (код шинжилгээ): top_manga_last_days()-ийн "viewed_at > N хоногийн
-- өмнө" хайлтад дэмжлэг vзvvлэх индекс (дээрх dedup индекс manga_id-аар эхэлдэг
-- тул энэ төрлийн бvх-мангын хугацааны шvvлтэд тус болохгvй).
create index if not exists manga_view_events_viewed_at_idx
  on public.manga_view_events (viewed_at);

-- ЗАСВАР #139 (migration_22): security definer + viewer_key dedup — эс тэгвэл
-- (1) RLS-д хамаарч staff биш энгийн уншигчийн vзэлт бодитоор нэмэгддэггvй,
-- (2) хэн ч давтан дуудаж vзэлтийг хиймлээр өсгөж чаддаг байсан.
drop function if exists public.increment_manga_views(bigint);
-- ЗАСВАР #190 (код шинжилгээ): өмнө нь void буцаадаг байсан тул клиент тал
-- (App.jsx) сервер бодитоор шинэ vзэлт тоолсон эсэхийг мэдэхгvйгээр vргэлж
-- optimistic +1 нэмдэг байв — нэг хэрэглэгч 30 минутын дотор хуудсыг 5 удаа
-- нээхэд дэлгэц дээр +5 харагдана (DB-д зөвхөн +1). Одоо boolean буцааж,
-- клиент зөвхөн ЖИНХЭНЭ шинэ тооллого vед л (true vед) +1 нэмнэ.
drop function if exists public.increment_manga_views(bigint, text);
create or replace function public.increment_manga_views(input_id bigint, viewer_key text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  effective_key text;
  recent_count int;
begin
  -- ЗАСВАР #163 (код шинжилгээ): хорлонтой клиент хэт урт viewer_key дамжуулж
  -- хvснэгт/индексийг бөглөхөөс сэргийлж 64 тэмдэгтээр таслав.
  effective_key := coalesce(auth.uid()::text, left(nullif(trim(viewer_key), ''), 64));
  if effective_key is null then
    return false;
  end if;

  select count(*) into recent_count
  from public.manga_view_events e
  where e.manga_id = input_id
    and e.viewer_key = effective_key
    and e.viewed_at > now() - interval '30 minutes';

  if recent_count > 0 then
    return false;
  end if;

  update public.mangas set views = views + 1 where id = input_id;
  insert into public.manga_view_events (manga_id, viewer_key) values (input_id, effective_key);
  return true;
end;
$$;

grant execute on function public.increment_manga_views(bigint, text) to anon, authenticated;

-- Сүүлийн N хоногт хамгийн их үзэгдсэн K мангаг буцаана
create or replace function public.top_manga_last_days(days_back int default 30, result_limit int default 10)
returns table(manga_id bigint, recent_views bigint)
language sql
stable
security definer
set search_path = public
as $$
  select manga_id, count(*) as recent_views
  from public.manga_view_events
  where viewed_at > now() - (days_back || ' days')::interval
  group by manga_id
  order by recent_views desc
  limit result_limit;
$$;

grant execute on function public.top_manga_last_days(int, int) to anon, authenticated;

-- ЗАСВАР #163: admin-ий "📊 СТАТИСТИК" таб — өдрийн аль цагт хамгийн их
-- уншигддагийг харуулна. Зөвхөн admin дуудаж болно (function дотроо шалгана).
create or replace function public.admin_views_by_hour(days_back int default 30)
returns table(hour_of_day int, view_count bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.has_any_role(auth.uid(), array['admin']) then
    raise exception 'Зөвхөн admin энэ vйлдлийг хийж болно.';
  end if;
  return query
    select extract(hour from (e.viewed_at at time zone 'Asia/Ulaanbaatar'))::int as hour_of_day,
           count(*) as view_count
    from public.manga_view_events e
    where e.viewed_at > now() - (days_back || ' days')::interval
    group by 1
    order by 1;
end;
$$;

grant execute on function public.admin_views_by_hour(int) to authenticated;

-- ЗАСВАР #163 (код шинжилгээ): 20,000 хэрэглэгчтэй vед ч manga_view_events
-- жилд ~35 сая мөр хvртэл өсөж болзошгvй тул хуучин (top_manga_last_days-ийн
-- дээд тал 30 хоногоос хамаагvй хуучин) мөрийг устгах purge функц. Үvнийг
-- өдөр бvр дуудахын тулд Supabase Dashboard → Database → Extensions-ээс
-- "pg_cron" өргөтгөлийг идэвхжvvлээд, доорх cron.schedule-ийг ГАРААР нэг
-- удаа ажиллуулна уу (доор тайлбар).
create or replace function public.purge_old_manga_view_events()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.manga_view_events where viewed_at < now() - interval '45 days';
$$;

-- ЗАСВАР #163 (код шинжилгээ): pg_cron нь SQL Editor-т ГАРААР "select
-- cron.schedule(...)" ажиллуулсан admin/superuser эрхээр л функцийг дуудна
-- (энгийн authenticated хэрэглэгчийн token-оор биш) тул энд grant шаардлагагvй
-- байсныг хассан — өмнө нь ямар ч нэвтэрсэн хэрэглэгч энэ функцийг дуудаж
-- чаддаг байв (хор багатай ч, зарчмын хувьд илvvц эрх).

-- ЗАСВАР #159-ийн App.jsx-д "top_manga_cache хvснэгтээс уншина" гэж бичсэн ч,
-- энэ хvснэгт хаана ч vvсгэгдээгvй байсан (App.jsx-ийн query алдаад
-- top_manga_last_days RPC руу чимээгvй fallback хийдэг байв — сайт эвдрээгvй
-- ч, зорьсон "цагийн 1 удаа тооцоод хадгалах" оновчлол бодитоор ажилладаггvй).
create table if not exists public.top_manga_cache (
  rank int primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  refreshed_at timestamptz not null default now()
);
alter table public.top_manga_cache enable row level security;
drop policy if exists "top_manga_cache_select_all" on public.top_manga_cache;
create policy "top_manga_cache_select_all" on public.top_manga_cache for select using (true);

create or replace function public.refresh_top_manga_cache()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.top_manga_cache;
  insert into public.top_manga_cache (rank, manga_id)
  select row_number() over (order by count(*) desc), manga_id
  from public.manga_view_events
  where viewed_at > now() - interval '30 days'
  group by manga_id
  order by count(*) desc
  limit 10;
end;
$$;

-- ============================================================
-- 8b) REELS — ЗАСВАР #113: "Юу уншихаа мэдэхгvй vv?" TikTok маягийн feed
-- ============================================================
create table if not exists public.reels (
  id bigint generated always as identity primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  video_url text not null,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.reel_likes (
  reel_id bigint not null references public.reels(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (reel_id, user_id)
);

-- ============================================================
-- 9) users.roles-ийг зөвхөн admin өөрчилж чадахаар хамгаална
-- ============================================================
create or replace function public.prevent_role_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- auth.uid() нь NULL байвал энэ бол SQL Editor эсвэл service_role-оор хийгдэж буй
  -- итгэмжлэгдсэн (trusted) өөрчлөлт гэсэн үг тул чөлөөтэй зөвшөөрнө. Харин browser-ээс
  -- нэвтэрсэн энгийн (admin биш) хэрэглэгч өөрийгөө/бусдыг admin/VIP болгох, эсвэл
  -- (ЗАСВАР #133, migration_18) өөрийн email-ээ өөр хэрэглэгчийнх рvv солиод admin-ийн
  -- "ЭРХ ОЛГОХ"-ыг хуурч ашиглахыг хориглоно.
  if new.roles is distinct from old.roles
     or new.is_vip is distinct from old.is_vip
     or new.vip_expires_at is distinct from old.vip_expires_at
     or new.email is distinct from old.email then
    if auth.uid() is not null and not exists (
      select 1 from public.users u where u.id = auth.uid() and 'admin' = any(u.roles)
    ) then
      new.roles := old.roles;
      new.is_vip := old.is_vip;
      new.vip_expires_at := old.vip_expires_at;
      new.email := old.email;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_role_escalation on public.users;
create trigger trg_prevent_role_escalation
  before update on public.users
  for each row execute function public.prevent_role_escalation();

-- ЗАСВАР #132 (migration_17): "энэ хэрэглэгч staff/admin мөн vv" гэдгийг шалгах
-- логикийг security definer функц рvv гаргав. Функц дуудагдахдаа RLS-г тойрдог
-- тул users-ийн SELECT policy дотроос ашиглахад "infinite recursion detected in
-- policy for relation users" (42P17) алдаа vvсэхгvй (raw "exists (select ... from
-- public.users)" ашиглавал users-ийн policy өөрийгөө дахин тооцоолох шаардлагатай
-- болж төгсгөлгvй давталтад ордог байсан). Мөн бусад бvх хvснэгтийн policy-д ч
-- энэ функцийг ашигласнаар Postgres нэг query-д функцийг дахин дахин биш нэг л
-- удаа тооцоолох боломжтой болж, гvйцэтгэл сайжирна (код шинжилгээ, ЗАСВАР #163).
create or replace function public.has_any_role(uid uuid, wanted text[])
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.users u where u.id = uid and u.roles && wanted
  );
$$;

grant execute on function public.has_any_role(uuid, text[]) to anon, authenticated;

-- ЗАСВАР #133 (migration_18): admin-ийн "ЭРХ ОЛГОХ"/"VIP ОЛГОХ"-д ашиглах, зөвхөн
-- auth.users (Supabase Auth-ийн баталгаажуулсан жинхэнэ имэйл)-ээр хайдаг функц —
-- итгэмжлэгдэхгvй public.users.email-ээр ХАЙХГvй (халдагч өөрийн email-ээ victim-ийнх
-- рvv "хуурч" бичиж, admin-аар өөртөө VIP олгуулах боломжийг хааж байна).
create or replace function public.admin_lookup_user_by_email(lookup_email text)
returns table(id uuid, email text, is_vip boolean, vip_expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.has_any_role(auth.uid(), array['admin']) then
    raise exception 'Зөвхөн admin энэ vйлдлийг хийж болно.';
  end if;
  return query
    select u.id, au.email::text, u.is_vip, u.vip_expires_at
    from auth.users au
    join public.users u on u.id = au.id
    where lower(au.email) = lower(trim(lookup_email))
    limit 1;
end;
$$;

grant execute on function public.admin_lookup_user_by_email(text) to authenticated;

-- ЗАСВАР #187 (код шинжилгээ): Gmail-ийн давхцлын шалгалтыг бvхэлд нь сервер
-- рvv (admin_grant_roles доор ашиглана) шилжvvлсэн тул энэ логикийг энд SQL-ээр
-- бичив (клиент талын helpers.js-ийн ижил зорилготой хуучин функц устгагдсан) —
-- Gmail нь local part дахь цэг болон "+alias"-ыг vл тооцдог.
create or replace function public.normalize_gmail_email(raw_email text)
returns text
language plpgsql
immutable
as $$
declare
  local_part text;
  domain_part text;
  norm text;
begin
  if raw_email is null then return ''; end if;
  norm := lower(trim(raw_email));
  local_part := split_part(norm, '@', 1);
  domain_part := split_part(norm, '@', 2);
  if domain_part = '' then return norm; end if;
  if domain_part in ('gmail.com', 'googlemail.com') then
    return replace(split_part(local_part, '+', 1), '.', '') || '@gmail.com';
  end if;
  return local_part || '@' || domain_part;
end;
$$;

-- ЗАСВАР #187: "ЭРХ ОЛГОХ" дэх Gmail давхцлын шалгалт клиент талын (async
-- ирдэг) staffUsers жагсаалт дээр vндэслэдэг байсан тул admin хуудас нээгээд
-- шууд (staffUsers хоосон vед) ЭРХ ОЛГОХ дарвал шалгалт алгасагдах race
-- condition-той байв. Одоо шалгалт болон эрх олгох (update) хоёуланг нь
-- НЭГ security definer RPC дотор (auth.users-ийн жинхэнэ баталгаажсан
-- имэйлээр) хийнэ.
create or replace function public.admin_grant_roles(target_user_id uuid, new_roles text[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_norm text;
  clash_email text;
begin
  if not public.has_any_role(auth.uid(), array['admin']) then
    raise exception 'Зөвхөн admin энэ vйлдлийг хийж болно.';
  end if;

  if coalesce(array_length(new_roles, 1), 0) > 0 then
    select public.normalize_gmail_email(au.email::text) into target_norm
    from auth.users au where au.id = target_user_id;

    select au.email::text into clash_email
    from public.users u
    join auth.users au on au.id = u.id
    where u.id <> target_user_id
      and coalesce(array_length(u.roles, 1), 0) > 0
      and public.normalize_gmail_email(au.email::text) = target_norm
    limit 1;

    if clash_email is not null then
      raise exception 'gmail_clash:%', clash_email;
    end if;
  end if;

  update public.users set roles = new_roles where id = target_user_id;
end;
$$;

grant execute on function public.admin_grant_roles(uuid, text[]) to authenticated;

-- ============================================================
-- 10) RLS идэвхжүүлэх + policy-үүд
-- ============================================================
alter table public.mangas enable row level security;
alter table public.users enable row level security;
alter table public.chapters enable row level security;
alter table public.chapter_images enable row level security;
alter table public.comments enable row level security;
alter table public.comment_likes enable row level security;
alter table public.reports enable row level security;
alter table public.manga_ratings enable row level security;
alter table public.payment_requests enable row level security;
alter table public.user_library enable row level security;
alter table public.reading_progress enable row level security;
alter table public.reels enable row level security;
alter table public.reel_likes enable row level security;

-- users
-- ЗАСВАР #126 (migration_14): "using (true)" хэн ч бvх хэрэглэгчийн мөрийг (имэйл
-- гэх мэт) бvрэн уншиж чаддаг байсан цоорхойг таслаж, зөвхөн өөрийн мөр/staff-аар
-- хязгаарлав. Сэтгэгдлийн эзэмшигчийн нэр/зураг vзvvлэхэд шаардлагатай нээлттэй
-- мэдээллийг (email биш) get_public_profiles() security definer функцээр дамжуулна.
drop policy if exists "users_select_all" on public.users;
drop policy if exists "users_select_own_or_staff" on public.users;
create policy "users_select_own_or_staff" on public.users for select
  using (
    auth.uid() = id
    or public.has_any_role(auth.uid(), array['admin','moderator','editor'])
  );

create or replace function public.get_public_profiles(user_ids uuid[])
returns table(id uuid, name text, avatar_url text, roles text[])
language sql
security definer
set search_path = public
stable
as $$
  select u.id, u.name, u.avatar_url, u.roles
  from public.users u
  where u.id = any(user_ids);
$$;

grant execute on function public.get_public_profiles(uuid[]) to anon, authenticated;

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own" on public.users for update
  using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "users_update_by_admin" on public.users;
create policy "users_update_by_admin" on public.users for update
  using (public.has_any_role(auth.uid(), array['admin']))
  with check (true);

-- ЗАСВАР #180 (код шинжилгээ): "users_update_own" нь МӨРИЙН түвшинд
-- (auth.uid()=id) л шалгадаг тул БАГАНЫГ хязгаарлахгvй — халдагч энгийн
-- хэрэглэгчээр { roles: ['admin'], is_vip: true } гэж өөрийн мөрөө шинэчилж,
-- өөрийгөө admin/VIP болгож чадах цоорхой байв. Бvх authenticated хэрэглэгч
-- Postgres талд НЭГ л role ("authenticated") ашигладаг тул баганы GRANT/REVOKE-ээр
-- admin эсэхийг ялгаж чадахгvй — BEFORE UPDATE trigger-ээр app-талын
-- has_any_role шалгалт хийж хамгаална.
create or replace function public.prevent_self_privilege_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.has_any_role(auth.uid(), array['admin']) then
    if (new.roles is distinct from old.roles)
       or (new.is_vip is distinct from old.is_vip)
       or (new.vip_expires_at is distinct from old.vip_expires_at) then
      raise exception 'Зөвхөн admin эрх/VIP төлөвийг өөрчилж болно.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_self_privilege_escalation on public.users;
create trigger trg_prevent_self_privilege_escalation
  before update on public.users
  for each row execute function public.prevent_self_privilege_escalation();

-- mangas
drop policy if exists "mangas_select" on public.mangas;
create policy "mangas_select" on public.mangas for select
  using (
    coalesce(is_hidden, false) = false
    or public.has_any_role(auth.uid(), array['admin','moderator','editor'])
  );

drop policy if exists "mangas_insert_staff" on public.mangas;
create policy "mangas_insert_staff" on public.mangas for insert
  with check (public.has_any_role(auth.uid(), array['admin','moderator','editor']));

-- ЗАСВАР #126/#136 (migration_14/20): editor нь мангыг шууд засах ёсгvй (нуух,
-- санал болгох гэх мэт зөвхөн admin/moderator-д зориулсан) тул admin/moderator-аар
-- хязгаарласан (хуучин нэр нь "mangas_update_staff" байсан бөгөөд editor-ийг ч
-- оруулдаг байсан цоорхойг migration_14-ээр таслав).
drop policy if exists "mangas_update_staff" on public.mangas;
drop policy if exists "mangas_update_moderate" on public.mangas;
create policy "mangas_update_moderate" on public.mangas for update
  using (public.has_any_role(auth.uid(), array['admin','moderator']));

-- chapters
-- ЗАСВАР #153 (migration_24): migration_14 эхлээд энд VIP/publish_at шалгалт
-- нэмсэн ч энэ нь БҮЛГИЙН МЕТАДАТА (гарчиг, дугаар, thumbnail)-ыг ч мөн VIP
-- бус хэрэглэгчээс далдалж, App.jsx-ийн "жагсаалтад харуулаад 🔒-ээр
-- түгжих" урсгалыг эвдсэн тул буцаагдсан — жинхэнэ хамгаалалт (VIP/цаг)
-- зөвхөн доорх "chapter_images_select" дээр (бодит хуудасны ЗУРАГ дээр) байна.
-- ЗАСВАР #163 (код шинжилгээ): is_hidden/pending_delete-тэй бvлгийн МЕТАДАТА
-- (гарчиг, дугаар) ч REST-ээр шууд query хийвэл харагддаг байсныг хаав — эдгээр
-- нь VIP/цагийн шалгалтаас (migration_24) ялгаатай нь ЕР НЬ ХАРАГДАХ учиргvй.
drop policy if exists "chapters_select" on public.chapters;
create policy "chapters_select" on public.chapters for select
  using (
    (status = 'published' and coalesce(is_hidden, false) = false and coalesce(pending_delete, false) = false)
    or public.has_any_role(auth.uid(), array['admin','moderator','editor'])
  );

-- ЗАСВАР #126 (migration_14): editor эрхтэй хэрэглэгч зөвхөн "pending" төлөвтэй
-- бvлэг оруулж болно (шууд "published" болгож чадахгvй); admin/moderator хязгааргvй.
drop policy if exists "chapters_insert_staff" on public.chapters;
create policy "chapters_insert_staff" on public.chapters for insert
  with check (
    public.has_any_role(auth.uid(), array['admin','moderator'])
    or (
      public.has_any_role(auth.uid(), array['editor'])
      and status = 'pending'
    )
  );

drop policy if exists "chapters_update_moderate" on public.chapters;
create policy "chapters_update_moderate" on public.chapters for update
  using (public.has_any_role(auth.uid(), array['admin','moderator']));

-- ЗАСВАР #163 (код шинжилгээ): editor өөрийн ЗАВСАРЛАГА ("pending") бvлгээ
-- (жишээ нь: pending_delete хvсэлт vvсгэх, эсвэл ирээдvйд засварлах) update
-- хийж чадахаар нээж өгнө — гэхдээ status='pending'-ээс өөр рvv (жишээ нь
-- шууд "published") шилжvvлж чадахгvй хэвээр (with check-ээр хамгаалагдсан).
drop policy if exists "chapters_update_editor_own_pending" on public.chapters;
create policy "chapters_update_editor_own_pending" on public.chapters for update
  using (
    public.has_any_role(auth.uid(), array['editor'])
    and status = 'pending'
  )
  with check (status = 'pending');

-- ЗАСВАР #135 (migration_19): moderator шууд (admin-ийг алгасаад) бvлэг устгаж
-- чадахгvй болгов — moderator/editor зөвхөн "УСТГАХ ХvСЭЛТ" (pending_delete=true)
-- vvсгэнэ, admin л эцсийн баталгаажуулалт хийж бодитоор устгана.
drop policy if exists "chapters_delete_moderate" on public.chapters;
drop policy if exists "chapters_delete_admin_only" on public.chapters;
create policy "chapters_delete_admin_only" on public.chapters for delete
  using (public.has_any_role(auth.uid(), array['admin']));

-- chapter_images (published бүлгийн зургийг хэн ч харна; staff бүгдийг; VIP/publish_at
-- шалгалт chapters_select-тэй ижил логикоор — ЗАСВАР #126, migration_14)
drop policy if exists "chapter_images_select" on public.chapter_images;
create policy "chapter_images_select" on public.chapter_images for select
  using (
    exists (
      select 1 from public.chapters c
      where c.id = chapter_id
        and (
          public.has_any_role(auth.uid(), array['admin','moderator','editor'])
          or (
            c.status = 'published'
            and (c.publish_at is null or c.publish_at <= now())
            and (
              not c.is_vip
              or exists (
                select 1 from public.users u where u.id = auth.uid()
                  and u.is_vip and (u.vip_expires_at is null or u.vip_expires_at > now())
              )
            )
          )
        )
    )
  );

-- ЗАСВАР #163 (код шинжилгээ): editor нь өөрийн upload урсгалд ("pending"
-- бvлэгт зураг нэмэх) л зориулагдсан байх ёстой байсан ч, chapter_id аль ч
-- (бусдын published) бvлгийнх байж болдог тул editor-т дурын нийтлэгдсэн
-- бvлэгт (vandalism-аар) зураг чихэх боломж vлдсэн байв.
drop policy if exists "chapter_images_insert_staff" on public.chapter_images;
create policy "chapter_images_insert_staff" on public.chapter_images for insert
  with check (
    public.has_any_role(auth.uid(), array['admin','moderator'])
    or (
      public.has_any_role(auth.uid(), array['editor'])
      and exists (select 1 from public.chapters c where c.id = chapter_id and c.status = 'pending')
    )
  );

-- ЗАСВАР #140 (migration_23): DELETE policy огт байгаагvй тул "БvЛЭГ ЗАСАХ"
-- цонхноос admin/moderator тодорхой хуудсыг хассан ч мөр бодитоор устгагдаагvй байв.
-- ЗАСВАР #163 (migration_30): editor өөрийн "pending" бvлгийн зургийг устгаж
-- чадахгvй байсныг insert/update policy-той адилхан хамрах хvрээгээр нээв
-- (өмнө нь editor "Бvтэн харах"-аас зураг устгасан ч, эцсийн Хадгалах vед
-- энэ policy editor-ыг хориглосон тул DB-с бодитоор устгагдаагvй байв).
drop policy if exists "chapter_images_delete_moderate" on public.chapter_images;
create policy "chapter_images_delete_moderate" on public.chapter_images for delete
  using (
    public.has_any_role(auth.uid(), array['admin','moderator'])
    or (
      public.has_any_role(auth.uid(), array['editor'])
      and exists (select 1 from public.chapters c where c.id = chapter_id and c.status = 'pending')
    )
  );

-- ЗАСВАР #163 (migration_30): UPDATE policy огт байгаагvй байсан тул "Бvтэн
-- харах" цонхны зураг СОЛИХ/ТАЙРАХ vйлдэл нь image_url-г шинэчлэхийг оролдоход
-- RLS-ээр 0 мөр таарч, error=null буцаж, клиент талд "амжилттай" мэт
-- харагдаад бодит DB-д хадгалагдаагvй байв. Insert policy-той ижил хамрах
-- хvрээгээр зөвшөөрнө.
drop policy if exists "chapter_images_update_staff" on public.chapter_images;
create policy "chapter_images_update_staff" on public.chapter_images for update
  using (
    public.has_any_role(auth.uid(), array['admin','moderator'])
    or (
      public.has_any_role(auth.uid(), array['editor'])
      and exists (select 1 from public.chapters c where c.id = chapter_id and c.status = 'pending')
    )
  )
  with check (
    public.has_any_role(auth.uid(), array['admin','moderator'])
    or (
      public.has_any_role(auth.uid(), array['editor'])
      and exists (select 1 from public.chapters c where c.id = chapter_id and c.status = 'pending')
    )
  );

-- ЗАСВАР #163 (код шинжилгээ): хуудасны дараалал солихдоо клиентээс 2N дараалсан
-- HTTP update явуулдаг байсан (сөрөг дугаарт шилжvvлээд, дараа нь эцсийн
-- дугаарт шилжvvлдэг 2 vе шаттай логик) — сvлжээ дундаа тасарвал сөрөг
-- page_number хагас vлдэж дараалал эвдэрч болзошгvй байв. Одоо тэр ХОЁР vе
-- шатыг НЭГ transaction дотор, нэг RPC дуудлагаар хийнэ.
create or replace function public.reorder_chapter_images(chapter_id_in bigint, image_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  i int;
begin
  if not public.has_any_role(auth.uid(), array['admin','moderator','editor']) then
    raise exception 'Зөвхөн staff энэ vйлдлийг хийж болно';
  end if;
  if exists (
    select 1 from unnest(image_ids) as iid
    where not exists (select 1 from public.chapter_images ci where ci.id = iid and ci.chapter_id = chapter_id_in)
  ) then
    raise exception 'Зарим зураг энэ бvлэгт харьяалагдахгvй байна';
  end if;

  for i in 1 .. coalesce(array_length(image_ids, 1), 0) loop
    update public.chapter_images set page_number = -i where id = image_ids[i];
  end loop;
  for i in 1 .. coalesce(array_length(image_ids, 1), 0) loop
    update public.chapter_images set page_number = i where id = image_ids[i];
  end loop;
end;
$$;

grant execute on function public.reorder_chapter_images(bigint, bigint[]) to authenticated;

-- comments
drop policy if exists "comments_select_all" on public.comments;
create policy "comments_select_all" on public.comments for select using (true);

-- ЗАСВАР #138 (migration_21): урт хязгаар (2000 тэмдэгт) + давтамжийн хязгаарлалт
-- (1 хэрэглэгч 5 секундэд дор хаяж 1 удаа л шинэ сэтгэгдэл бичиж болно) — эс бол
-- script-ээр хязгааргvй тооны сэтгэгдэл нэг зэрэг илгээж feed-ийг flood хийх боломжтой.
alter table public.comments
  drop constraint if exists comments_content_length;
alter table public.comments
  add constraint comments_content_length check (char_length(content) <= 2000);

drop policy if exists "comments_insert_own" on public.comments;
create policy "comments_insert_own" on public.comments for insert
  with check (auth.uid() = user_id);

-- ЗАСВАР #185 (код шинжилгээ): 5 секундийн rate-limit-ийг өмнө нь RLS policy-ийн
-- WITH CHECK дотор шалгадаг байсан тул зөрчигдвол RLS-ийн ерөнхий "new row violates
-- row-level security policy" алдаа буцдаг байв — клиент код ЯМАР Ч ийм алдааг (жинхэнэ
-- эрхийн зөрчил ч гэсэн) автоматаар "хэт хурдан байна" гэж буруу тайлбарладаг байсан.
-- Одоо rate-limit-ийг тусад нь trigger-ээр шалгаж, ялгаатай ('rate_limited') алдаа
-- буцаана — RLS зөрчил бол жинхэнэ (өөр шалтгаантай) алдаа хэвээр vлдэнэ.
create or replace function public.enforce_comment_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1 from public.comments c
    where c.user_id = new.user_id
      and c.created_at > now() - interval '5 seconds'
  ) then
    raise exception 'rate_limited';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_comment_rate_limit on public.comments;
create trigger trg_enforce_comment_rate_limit
  before insert on public.comments
  for each row execute function public.enforce_comment_rate_limit();

drop policy if exists "comments_delete_own_or_mod" on public.comments;
create policy "comments_delete_own_or_mod" on public.comments for delete
  using (
    auth.uid() = user_id
    or public.has_any_role(auth.uid(), array['admin','moderator'])
  );

-- comment_likes
drop policy if exists "comment_likes_select_all" on public.comment_likes;
create policy "comment_likes_select_all" on public.comment_likes for select using (true);

drop policy if exists "comment_likes_insert_own" on public.comment_likes;
create policy "comment_likes_insert_own" on public.comment_likes for insert
  with check (auth.uid() = user_id);

drop policy if exists "comment_likes_delete_own" on public.comment_likes;
create policy "comment_likes_delete_own" on public.comment_likes for delete
  using (auth.uid() = user_id);

-- reports
drop policy if exists "reports_insert_own" on public.reports;
create policy "reports_insert_own" on public.reports for insert
  with check (auth.uid() = reporter_id);

drop policy if exists "reports_select_mod" on public.reports;
create policy "reports_select_mod" on public.reports for select
  using (public.has_any_role(auth.uid(), array['admin','moderator']));

drop policy if exists "reports_update_mod" on public.reports;
create policy "reports_update_mod" on public.reports for update
  using (public.has_any_role(auth.uid(), array['admin','moderator']));

-- payment_requests
drop policy if exists "payment_requests_insert_own" on public.payment_requests;
create policy "payment_requests_insert_own" on public.payment_requests for insert
  with check (auth.uid() = user_id);

drop policy if exists "payment_requests_select_own_or_admin" on public.payment_requests;
create policy "payment_requests_select_own_or_admin" on public.payment_requests for select
  using (
    auth.uid() = user_id
    or public.has_any_role(auth.uid(), array['admin'])
  );

drop policy if exists "payment_requests_update_admin" on public.payment_requests;
create policy "payment_requests_update_admin" on public.payment_requests for update
  using (public.has_any_role(auth.uid(), array['admin']));

-- ЗАСВАР #163 (код шинжилгээ): "VIP олгох" + "хvсэлтийг approved болгох" 2
-- салангид update-ийг НЭГ transaction дотор, мөр түгжиж (for update) хийдэг RPC —
-- эс бол эхнийх нь амжилттай, хоёр дахь нь fail болвол хvсэлт "pending" хэвээр
-- vлдэж, admin дахин "БАТЛАХ" дарахад VIP ДАВХАР нэмэгддэг эрсдэлтэй байсан.
create or replace function public.approve_payment_request(request_id bigint, vip_days int)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  req record;
  base timestamptz;
begin
  if not public.has_any_role(auth.uid(), array['admin']) then
    raise exception 'Зөвхөн admin батлах эрхтэй';
  end if;

  select * into req from public.payment_requests where id = request_id for update;
  if req is null then
    raise exception 'Хvсэлт олдсонгvй';
  end if;
  if req.status <> 'pending' then
    raise exception 'Энэ хvсэлт аль хэдийн шийдэгдсэн байна';
  end if;

  select case
           when u.is_vip and u.vip_expires_at is not null and u.vip_expires_at > now()
           then u.vip_expires_at
           else now()
         end
    into base
    from public.users u where u.id = req.user_id;

  update public.users
    set is_vip = true, vip_expires_at = base + (vip_days || ' days')::interval
    where id = req.user_id;

  update public.payment_requests
    set status = 'approved', reviewed_at = now(), reviewed_by = auth.uid()
    where id = request_id;
end;
$$;

grant execute on function public.approve_payment_request(bigint, int) to authenticated;

-- user_library / reading_progress
drop policy if exists "user_library_own" on public.user_library;
create policy "user_library_own" on public.user_library for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "reading_progress_own" on public.reading_progress;
create policy "reading_progress_own" on public.reading_progress for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- manga_ratings
drop policy if exists "manga_ratings_select_all" on public.manga_ratings;
create policy "manga_ratings_select_all" on public.manga_ratings for select using (true);

drop policy if exists "manga_ratings_own" on public.manga_ratings;
create policy "manga_ratings_own" on public.manga_ratings for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ЗАСВАР #136 (migration_20): "is_recommended" (нvvр хэсгийн "САНАЛ БОЛГОХ" hero)
-- UI дээр зөвхөн isAdmin-д харагддаг тул RLS-ээр ч мөн зөвхөн admin-аар
-- хязгаарлав — moderator mangas_update_moderate эрхтэй ч энэ баганыг өөрчилбол
-- чимээгvй хуучин утга руугаа буцна.
create or replace function public.prevent_unauthorized_manga_recommend()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.is_recommended is distinct from old.is_recommended then
    if auth.uid() is not null and not public.has_any_role(auth.uid(), array['admin']) then
      new.is_recommended := old.is_recommended;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prevent_unauthorized_manga_recommend on public.mangas;
create trigger trg_prevent_unauthorized_manga_recommend
  before update on public.mangas
  for each row execute function public.prevent_unauthorized_manga_recommend();

-- reels — зөвхөн admin/moderator нэмж/устгаж болно, бvгд хардаг
drop policy if exists "reels_select_all" on public.reels;
create policy "reels_select_all" on public.reels for select using (true);

drop policy if exists "reels_moderator_write" on public.reels;
create policy "reels_moderator_write" on public.reels for all
  using (public.has_any_role(auth.uid(), array['admin','moderator']))
  with check (public.has_any_role(auth.uid(), array['admin','moderator']));

-- reel_likes
drop policy if exists "reel_likes_select_all" on public.reel_likes;
create policy "reel_likes_select_all" on public.reel_likes for select using (true);

drop policy if exists "reel_likes_own" on public.reel_likes;
create policy "reel_likes_own" on public.reel_likes for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ============================================================
-- 11) STORAGE — "manga-site" bucket (avatar/poster/banner/chapter зургууд)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('manga-site', 'manga-site', true)
on conflict (id) do nothing;

-- ЗАСВАР #94-ээр upload бvгд Cloudflare R2 руу шилжсэн (upload-to-r2 edge
-- function-оор дамждаг) тул энэ Supabase Storage "manga-site" bucket vнэндээ
-- ашиглагдахгvй болсон. Гэвч (кэшлэгдсэн хуучин холбоос гэх мэт зvйлсийг
-- эвдэхгvйн тулд) bucket-ыг бvрэн устгахгvй, зөвхөн нээлттэй УПЛОАД policy-г
-- (өмнө нь ямар ч нэвтэрсэн хэрэглэгч дурын нэр/хэмжээгээр чөлөөтэй upload
-- хийж чаддаг, vнэгvй file-hosting/DoS-зардлын цоорхой байсан) хассан.
-- Хэрэв энэ bucket-ыг vнэхээр огт хэрэглэдэггvй бол Dashboard-аас бvрэн
-- устгаж/private болгож болно.
drop policy if exists "manga_site_public_read" on storage.objects;
create policy "manga_site_public_read" on storage.objects for select
  using (bucket_id = 'manga-site');

drop policy if exists "manga_site_avatar_upload" on storage.objects;
drop policy if exists "manga_site_staff_upload" on storage.objects;

-- Анхны admin-аа гараар тохируулна уу (доор жишээ — өөрийн имэйлээр солино):
-- update public.users set roles = array['admin'] where email = 'ТАНЫ_ИМЭЙЛ@жишээ.com';

-- ============================================================
-- 12) ГvЙЦЭТГЭЛ (performance) — ЗАСВАР #163 (код шинжилгээ): 20,000 хэрэглэгч/
--     2,000 бvлгийн хэмжээнд Postgres-д "жижиг ачаалал" ч, өсөхөөс ӨМНӨ хийвэл
--     зохих индексvvд. Postgres нь FK (foreign key)-д АВТОМАТААР индекс vvсгэдэггvй.
-- ============================================================
create index if not exists chapters_manga_idx on public.chapters (manga_id);
-- ЗАСВАР #183 (код шинжилгээ): (manga_id, chapter_number) хосол давхардахгvй байх
-- unique хязгаарлалт байгаагvй тул .maybeSingle() ашигладаг унших route ижил
-- дугаартай 2 бvлэг vvсвэл алдаа шиднэ (олон мөр буцаана). Хэрэв энэ мөр
-- "duplicate key" алдаагаар унавал, эхлээд давхардсан бvлгvvдийг олж (доорх
-- query-г SQL Editor-т ажиллуулж vзнэ vv) цэвэрлэсний дараа дахин ажиллуулна:
--   select manga_id, chapter_number, count(*) from public.chapters
--   group by manga_id, chapter_number having count(*) > 1;
create unique index if not exists chapters_manga_chapter_unique_idx on public.chapters (manga_id, chapter_number);
create index if not exists chapter_images_chapter_idx on public.chapter_images (chapter_id, page_number);
create index if not exists comments_chapter_idx on public.comments (chapter_id, created_at desc);
create index if not exists comments_manga_idx on public.comments (manga_id, created_at desc);
-- ЗАСВАР #163: comments_insert_own policy-ийн 5 секундийн rate-limit дэд query-д
-- ашиглагдана (user_id + created_at-аар тухайн хэрэглэгчийн сvvлийн сэтгэгдлvvдийг
-- хайдаг тул сэтгэгдэл олон мянга болоход энэ индексгvйгээр seq scan удаашрана).
create index if not exists comments_user_recent_idx on public.comments (user_id, created_at desc);

-- ============================================================
-- 13) pg_cron-оор автоматаар ажиллуулах 2 зvйл (сонголттой, гэхдээ 20,000+
--     хэрэглэгчтэй болмогц зайлшгvй хэрэгтэй болно):
--
--   1) Supabase Dashboard → Database → Extensions → "pg_cron"-г идэвхжvvл
--   2) Дараах 2 командыг SQL Editor-т НЭГ УДАА гараар ажиллуул:
--
--      select cron.schedule(
--        'purge-manga-view-events',
--        '0 3 * * *',  -- өдөр бvр шөнийн 03:00 (UTC)
--        $$select public.purge_old_manga_view_events()$$
--      );
--
--      select cron.schedule(
--        'refresh-top-manga-cache',
--        '0 * * * *',  -- цаг тутам
--        $$select public.refresh_top_manga_cache()$$
--      );
--
--   Идэвхжvvлээгvй ч сайт хэвийн ажиллана (нvvр хуудасны "Санал болгох" fallback-аар
--   top_manga_last_days RPC руу ордог, manga_view_events л удаан хугацаанд
--   (жилд ойролцоогоор 35 сая мөр хvртэл) томорсоор байх болно).
-- ============================================================
