-- ШИНЭ (хэрэглэгчийн хvсэлт): "Нийтийн чат" дангаараа биш, БvРЭН чат систем
-- байх ёстой гэдгийг тодруулсны дагуу — хэрэглэгчид хоорондоо ХУВИЙН зурвас
-- (1-1 DM) бичиж, тэр дундаа манга хуваалцаж, стикер/emoji илгээж, тодорхой
-- мессежид "reply" (иш татаж хариулах) хийж, ❤️ дарж болох бvрэлдэхvvн хэсгvvд.

-- 1) direct_messages ---------------------------------------------------------
create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.users(id) on delete cascade,
  recipient_id uuid not null references public.users(id) on delete cascade,
  message_type text not null default 'text', -- text | sticker | manga_share
  content text,
  sticker_url text,
  manga_id bigint references public.mangas(id) on delete set null,
  reply_to_id bigint references public.direct_messages(id) on delete set null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.direct_messages
  drop constraint if exists direct_messages_type_check;
alter table public.direct_messages
  add constraint direct_messages_type_check check (message_type in ('text', 'sticker', 'manga_share'));

alter table public.direct_messages
  drop constraint if exists direct_messages_content_length;
alter table public.direct_messages
  add constraint direct_messages_content_length check (content is null or char_length(content) <= 1000);

alter table public.direct_messages enable row level security;

drop policy if exists "direct_messages_select_participant" on public.direct_messages;
create policy "direct_messages_select_participant" on public.direct_messages for select
  using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists "direct_messages_insert_own" on public.direct_messages;
create policy "direct_messages_insert_own" on public.direct_messages for insert
  with check (auth.uid() = sender_id);

drop policy if exists "direct_messages_update_recipient_read" on public.direct_messages;
create policy "direct_messages_update_recipient_read" on public.direct_messages for update
  using (auth.uid() = recipient_id)
  with check (auth.uid() = recipient_id);

-- ЗАСВАР: мессежийн төрөл (text/sticker/manga_share)-ээс хамааран шаардлагатай
-- талбарууд орсон эсэх, өөрөө өөртөө бичихгvй байх, reply_to_id нь ЯГ ХОЁРЫН
-- хоорондох (гуравдагч хvний биш) мессеж рvv л заана уу гэдгийг серверт шалгана.
create or replace function public.validate_direct_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.sender_id = new.recipient_id then
    raise exception 'cannot_message_self';
  end if;
  if new.message_type = 'text' and (new.content is null or length(trim(new.content)) = 0) then
    raise exception 'empty_message';
  end if;
  if new.message_type = 'sticker' and new.sticker_url is null then
    raise exception 'missing_sticker';
  end if;
  if new.message_type = 'manga_share' and new.manga_id is null then
    raise exception 'missing_manga';
  end if;
  if new.reply_to_id is not null and not exists (
    select 1 from public.direct_messages dm
    where dm.id = new.reply_to_id
      and ((dm.sender_id = new.sender_id and dm.recipient_id = new.recipient_id)
        or (dm.sender_id = new.recipient_id and dm.recipient_id = new.sender_id))
  ) then
    raise exception 'invalid_reply';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_validate_direct_message on public.direct_messages;
create trigger trg_validate_direct_message
  before insert on public.direct_messages
  for each row execute function public.validate_direct_message();

-- Спам хамгаалалт: chat_messages-тэй ижил зарчмаар 2 секунд тутам 1 мессеж.
create or replace function public.enforce_dm_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1 from public.direct_messages dm
    where dm.sender_id = new.sender_id
      and dm.created_at > now() - interval '2 seconds'
  ) then
    raise exception 'rate_limited';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_dm_rate_limit on public.direct_messages;
create trigger trg_enforce_dm_rate_limit
  before insert on public.direct_messages
  for each row execute function public.enforce_dm_rate_limit();

create index if not exists direct_messages_conversation_idx on public.direct_messages (sender_id, recipient_id, created_at);
create index if not exists direct_messages_recipient_unread_idx on public.direct_messages (recipient_id, read_at);

-- 2) direct_message_likes (❤️) -----------------------------------------------
create table if not exists public.direct_message_likes (
  message_id bigint not null references public.direct_messages(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

alter table public.direct_message_likes enable row level security;

drop policy if exists "dm_likes_select_participant" on public.direct_message_likes;
create policy "dm_likes_select_participant" on public.direct_message_likes for select
  using (
    exists (
      select 1 from public.direct_messages dm
      where dm.id = message_id and (dm.sender_id = auth.uid() or dm.recipient_id = auth.uid())
    )
  );

drop policy if exists "dm_likes_insert_participant" on public.direct_message_likes;
create policy "dm_likes_insert_participant" on public.direct_message_likes for insert
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.direct_messages dm
      where dm.id = message_id and (dm.sender_id = auth.uid() or dm.recipient_id = auth.uid())
    )
  );

drop policy if exists "dm_likes_delete_own" on public.direct_message_likes;
create policy "dm_likes_delete_own" on public.direct_message_likes for delete
  using (auth.uid() = user_id);

-- 3) хvмvvсийг нэрээр нь хайх (шинэ зурвас эхлvvлэхэд) ------------------------
create or replace function public.search_users(query_in text)
returns table(id uuid, name text, avatar_url text)
language sql
security definer
set search_path = public
stable
as $$
  select u.id, u.name, u.avatar_url
  from public.users u
  where u.id <> auth.uid()
    and u.name is not null
    and u.name ilike '%' || query_in || '%'
  order by u.name
  limit 10;
$$;

grant execute on function public.search_users(text) to authenticated;

-- 4) "Миний зурвас" (inbox) — хvн бvртэй хийсэн сvvлийн мессеж + уншаагvй тоо --
create or replace function public.get_dm_inbox()
returns table(
  partner_id uuid,
  partner_name text,
  partner_avatar_url text,
  last_message text,
  last_message_type text,
  last_created_at timestamptz,
  unread_count bigint
)
language sql
security definer
set search_path = public
stable
as $$
  with mine as (
    select
      case when sender_id = auth.uid() then recipient_id else sender_id end as partner_id,
      content, message_type, created_at
    from public.direct_messages
    where sender_id = auth.uid() or recipient_id = auth.uid()
  ),
  ranked as (
    select *, row_number() over (partition by partner_id order by created_at desc) as rn
    from mine
  )
  select
    r.partner_id,
    u.name,
    u.avatar_url,
    r.content,
    r.message_type,
    r.created_at,
    (select count(*) from public.direct_messages dm2
       where dm2.sender_id = r.partner_id and dm2.recipient_id = auth.uid() and dm2.read_at is null) as unread_count
  from ranked r
  join public.users u on u.id = r.partner_id
  where r.rn = 1
  order by r.created_at desc;
$$;

grant execute on function public.get_dm_inbox() to authenticated;

create or replace function public.get_dm_unread_count()
returns bigint
language sql
security definer
set search_path = public
stable
as $$
  select count(*) from public.direct_messages
  where recipient_id = auth.uid() and read_at is null;
$$;

grant execute on function public.get_dm_unread_count() to authenticated;

create or replace function public.mark_dm_read(partner_id_in uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.direct_messages
    set read_at = now()
    where recipient_id = auth.uid() and sender_id = partner_id_in and read_at is null;
$$;

grant execute on function public.mark_dm_read(uuid) to authenticated;
