-- ШИНЭ (хэрэглэгчийн хvсэлт): "Санал хvсэлт" болон "Даалгавар" цонхнуудыг
-- саoйжруулах багц — 4 шинэ DB бvрэлдэхvvн хэсэг:
--   1) feedback_messages — санал хvсэлт бvр дээр хэрэглэгч/admin хоорондын
--      thread маягийн харилцан яриа (admin хариулахад хэрэглэгчид мэдэгдэнэ).
--   2) tasks.expires_at — заавал биш, тавигдвал даалгаварт countdown timer.
--   3) get_task_leaderboard RPC — хамгийн олон даалгавар биелvvлсэн
--      хэрэглэгчдийн нээлттэй leaderboard.
--   4) chat_messages — сайт даяарх "Нийтийн чат".

-- 1) feedback_messages ------------------------------------------------------
create table if not exists public.feedback_messages (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null references public.feedback(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  is_staff boolean not null default false,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.feedback_messages
  drop constraint if exists feedback_messages_length;
alter table public.feedback_messages
  add constraint feedback_messages_length check (char_length(message) <= 1000 and char_length(message) > 0);

alter table public.feedback_messages enable row level security;

drop policy if exists "feedback_messages_select" on public.feedback_messages;
create policy "feedback_messages_select" on public.feedback_messages for select
  using (
    exists (select 1 from public.feedback f where f.id = feedback_id and f.user_id = auth.uid())
    or public.has_any_role(auth.uid(), array['admin','moderator'])
  );

drop policy if exists "feedback_messages_insert" on public.feedback_messages;
create policy "feedback_messages_insert" on public.feedback_messages for insert
  with check (
    auth.uid() = user_id
    and (
      exists (select 1 from public.feedback f where f.id = feedback_id and f.user_id = auth.uid())
      or public.has_any_role(auth.uid(), array['admin','moderator'])
    )
  );

-- ЗАСВАР: is_staff-г клиентээс vнэн зөв илгээнэ гэдэгт найдахгvй (хvн хуурч
-- болно), оронд нь insert vед сервер дээр өөрөө тодорхойлно.
create or replace function public.set_feedback_message_staff_flag()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.is_staff := public.has_any_role(new.user_id, array['admin','moderator']);
  return new;
end;
$$;

drop trigger if exists trg_set_feedback_message_staff_flag on public.feedback_messages;
create trigger trg_set_feedback_message_staff_flag
  before insert on public.feedback_messages
  for each row execute function public.set_feedback_message_staff_flag();

create index if not exists feedback_messages_feedback_idx on public.feedback_messages (feedback_id, created_at);

-- 2) tasks.expires_at (countdown timer, сонголттой) --------------------------
alter table public.tasks add column if not exists expires_at timestamptz;

-- 3) leaderboard ---------------------------------------------------------
-- ЗАСВАР: task_claims-ийн select policy зөвхөн "өөрийнхөө мөр" гэж хязгаарласан
-- тул бусад хэрэглэгчийн явцыг клиент шууд харж чадахгvй — security definer
-- RPC-ээр (зөвхөн нэр/avatar/тоо, бусад хувийн мэдээлэлгvй) нээлттэй болгоно.
create or replace function public.get_task_leaderboard(limit_in int default 10)
returns table(user_id uuid, name text, avatar_url text, completed_count bigint)
language sql
security definer
set search_path = public
stable
as $$
  select u.id, u.name, u.avatar_url, count(tc.task_id) as completed_count
  from public.task_claims tc
  join public.users u on u.id = tc.user_id
  group by u.id, u.name, u.avatar_url
  order by completed_count desc, u.id
  limit limit_in;
$$;

grant execute on function public.get_task_leaderboard(int) to authenticated;

-- 4) chat_messages (Нийтийн чат) --------------------------------------------
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.chat_messages
  drop constraint if exists chat_messages_length;
alter table public.chat_messages
  add constraint chat_messages_length check (char_length(message) <= 500 and char_length(message) > 0);

alter table public.chat_messages enable row level security;

drop policy if exists "chat_messages_select_authenticated" on public.chat_messages;
create policy "chat_messages_select_authenticated" on public.chat_messages for select
  using (auth.uid() is not null);

drop policy if exists "chat_messages_insert_own" on public.chat_messages;
create policy "chat_messages_insert_own" on public.chat_messages for insert
  with check (auth.uid() = user_id);

drop policy if exists "chat_messages_delete_own_or_staff" on public.chat_messages;
create policy "chat_messages_delete_own_or_staff" on public.chat_messages for delete
  using (auth.uid() = user_id or public.has_any_role(auth.uid(), array['admin','moderator']));

-- Спам хамгаалалт: 2 секунд тутам 1 мессеж (feedback-ийн 10 секундээс богино,
-- учир нь чат амьд харилцаа тул түvнээс шаардлага өөр).
create or replace function public.enforce_chat_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1 from public.chat_messages c
    where c.user_id = new.user_id
      and c.created_at > now() - interval '2 seconds'
  ) then
    raise exception 'rate_limited';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_chat_rate_limit on public.chat_messages;
create trigger trg_enforce_chat_rate_limit
  before insert on public.chat_messages
  for each row execute function public.enforce_chat_rate_limit();

create index if not exists chat_messages_created_idx on public.chat_messages (created_at desc);
